### ISSUE TITLE
Invoice Template Settings (Logo Issues)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1004]
After uploading a logo, If user clicks on any logo size button (i.e., "S", "M" or "L"), then logo disappears from the preview section and user is unable to Update a logo image on template.

Also, no API is called when user clicks on Update button near "L" button.

ENV: TEST

**Comment by sagarnankani** [comment]
PFA screenshot.
![logo_size.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e49b9d2cbd90a095ecfd0fe64de29b234324676b5ee17e71d3b371be1579515a571dae47585f4df9fa882fa1b56e62964e49bc8f3900299f7744eeaa880dbe08b0218e4c85b0bb8348c5e13d2ce699c2.PNG)

**Comment by sagarnankani** [comment]
![inv_logo_up.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e19a8c1c8e8cae80d6aa53e611b2843b492d762a10e17132d0e27eef1b7a560d5f4ba4125a5944fcf08c28a7b23b73d84e17ff933c0120996048e6edc00db513bb27814e80b5bc8c4bc9ed3526e48a8c5d73.PNG)

**Comment by mustafa-walkover** [comment]
done
