### ISSUE TITLE
Create/Update Account ("Closing Balance" field issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1011]
While Creating/Updating an account "Closing Balance" field is being displayed unnecessarily.

Please remove it.

ENV: PROD
Please fix this ASAP.

**Comment by sagarnankani** [comment]
PFA screenshot.
![closing_balance.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46eb9895308b8daeb0ebbe4fa553f3916b0a65633b0ba92e7391a172fd177a575f561fab13585a4caffb8f2ba6bf39738b580cee837f4366846c4ff8e7df46f554f832815d84bfb68b49c3e83a25ee8b884c371d000ac4.PNG)

**Comment by mustafa-walkover** [comment]
Not a bug
