### ISSUE TITLE
Create Ledger (Currency Conversion API not being called)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1052]
When user creates a ledger entry, please check currency of all the accounts involved in the ledger entry. If currency of any of these accounts in null, then consider its currency to be the same as that of the company.
And if currency of two or more accounts is different, then please call currency conversion API.

ENV: PROD
Please fix this ASAP

**Comment by apmeena** [comment]
Done.
