### ISSUE TITLE
Invoice Lock Date - Incorrect Date is passed in API request

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1055]
Invoice Lock Date - Incorrect Date is passed in API request

PFA screenshot
ENV: PROD
Please fix this ASAP

**Comment by sagarnankani** [comment]
![INVOICE LOCK DATE.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46c1baac0caba08ccfc590608f1dd4b51d63653f6b14b1247a80e03cfd1839540e594ea5105f0d44f9f1da29a0b63c798f5f0ae9d66e0d66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3e24e4898e48371c001e88ed10.png)

**Comment by apmeena** [comment]
I am not able to reproduce it. Testest on production also. Working fine.

**Comment by walkover101** [comment]
@sagarnankani pls check if is this fix please move to "review on test" or reopen it

**Comment by mustafa-walkover** [comment]
checked by @sagarnankani
