### ISSUE TITLE
Update Company (State Code is not being selected)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1063]
While Updating Company Profile, State Code is not being selected automatically on entering GSTIN.

Please fix this ASAP.
ENV: PROD

PFA screenshot.

**Comment by sagarnankani** [comment]
![statecodenotsel.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46fb809b378780a68becb14cb04ef5986b0a65633b0ba92e7391a172fd177a575f561fab13585a4caffb8f2ba6bf39738b580cee837f4366846c4ff8e7df46f554f832815d84beb68b49c3e93923e58a884e3a16020ac4.PNG)

**Comment by sagarnankani** [comment]
Also, if user selects only State from drop down (and doesn't provide GSTIN), then state name is being passed in "stateCode" param instead of state code.
Please fix this issue as well.

**Comment by mustafa-walkover** [comment]
done
