### ISSUE TITLE
Contact Module (Search works only on current page)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1064]
In Contact Module, Search works only on current page. This is incorrect. Searching should be done on all pages and all relevant results should come up in results.

ENV: PROD
Please fix this ASAP.

**Comment by apmeena** [comment]
Please provide the API and related information.

**Comment by apmeena** [comment]
Note: NOT done form API side, this card is on hold.

**Comment by sagarnankani** [comment]
@mustafa-walkover 
This is done from API end.
//API Details
url?q=

Sample Request URL: http://apitest.giddh.com/v2/company/adityaindia15447087091950c4uwl/groups/sundrydebtors/account-balances?page=1&count=20&refresh=true&q=multi

Currently search is working from UI end.
Please send the aforesaid query param "q" in request URL along with the value entered by user.

**Comment by walkover101** [comment]
I am not able to test as pagination is not working in contact section

**Comment by Eagle-Giddh** [comment]
Fixed
