### ISSUE TITLE
Need to call groups-with-accounts API

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1070]
Please call "groups-with-accounts" API (https://api.giddh.com/company/ciprodindore150735619967307rkv5/groups-with-accounts?q=
) everywhere instead of following.
/company/newtalindore15289779274070mfj3f/groups/currentassets/subgroups

As the above mentioned API is deprecated.

ENV: PROD

**Comment by mustafa-walkover** [comment]
but in `groups-with-accounts?q=`this API, we are not getting, all the groups of current assets. it is mostly needed while creating account from sales module, where we list accounts from debtors & creditors only..

**Comment by mustafa-walkover** [comment]
Your suggestions will be appreciable

**Comment by sagarnankani** [comment]
@mustafa-walkover Please proceed as per gaurav sir's suggestion.
