### ISSUE TITLE
All Date Picker Fields (Duration Issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1074]
Duration mentioned on all the date picker fields on web based app need to be replaced with the duration mentioned on date picker on mobile app.

ENV: PROD
Please fix this ASAP.

PFA screenshot for details.

**Comment by sagarnankani** [comment]
![dp_mob.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ec84a52e8d81ebc3abaf51ab57f5973d047d317c05f57b2984b42aef1723025d594eac485d5c45f8fe8a79b4aa2e32db025fb28c341521842f1bbeb98b15be04b9218c4b82b5bf8a4ac3e92f68.PNG)

**Comment by mustafa-walkover** [comment]
@sagarnankani please add this card to task
