### ISSUE TITLE
Create Trigger ("Invalid Filter" error)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1078]
"Invalid Filter" error is received in response of Create Trigger API when user provides "amountLessThan" value for filter param.

Please send filter value as "amountSmallerThan" in place of "amountLessThan"

//API Details:
Request URL: http://apitest.giddh.com/company/newsncindore15000172022770ygv88/triggers
Request Method: POST
Status Code: 400
Request:
{"entity":"group","entityType":"","scope":"entry","action":"webhook","name":"zvsdvsdvdsfasfasf","entityUniqueName":"otherincome","filter":"amountLessThan","value":222,"url":"htps://www.google.com","description":"ddassdasd"}

Response:
{"status":"error","code":"INVALID_FILTER","message":"Invalid Filter"}

**Comment by apmeena** [comment]
Done
