### ISSUE TITLE
Create Ledger - Rate Conversion issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1102]
If company currency is USD and account's currency is INR, then, while creating a ledger entry, conversion rate is found for INR to USD instead of USD to INR.
So, if user entered "900" in amount box (INR), then in converted amount box, "61983.00" value is provided automatically. Which is incorrect.

PFA screenshot.
Please fix this ASAP.
PFA screenshot.

**Comment by sagarnankani** [comment]
![Rateconv.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46da958e26818ca799abf301b44fff9e2c4533317346f62a26d5ba29e8402b54570c4caa41585641fff88d2ca5e42e6c981e5ab38532022d8c6853beb2901eb60bbb25884d84b3b9824fc1ea3b23f5c6.png)

**Comment by apmeena** [comment]
![Screen Shot 2018-07-24 at 12.35.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a61edd7aaed3200135a8afb/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f76b7191a379ed0c2854415c4cbc21254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e34954a2133761e277366e0a.png)

**Comment by apmeena** [comment]
Request URL: `http://apitest.giddh.com/company/newsncindore15000172022770ygv88/currency-converter/USD/INR`
Request Method: `GET`
Status Code: `200` 

Response:
`{"status":"success","body":0.01}`

**Comment by apmeena** [comment]
Company currency is: `USD`
Account currency is: `INR`

**Comment by apmeena** [comment]
@sagarnankani,  I don't see any calculation mistake here, please check my screenshot and let me know what t do.

**Comment by sagarnankani** [comment]
Checked on Test. This is fixed.

**Comment by sagarnankani** [comment]
Checked on PROD. This is fixed. Hence closing this.
