### ISSUE TITLE
Manage Groups & Accounts - Currency issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1104]
Please provide an option to change currency of accounts such as Cash, Sales, etc.

Currently, currency text box is displayed only for Sundry Debtors/Creditors Accounts, that too when their country is a foreign country.
This is incorrect.

Currency field should be displayed for all accounts, irrespective of account's country.

ENV: PROD
Please fix this ASAP

**Comment by mustafa-walkover** [comment]
ok but currently working was the requirement

**Comment by mustafa-walkover** [comment]
done
