### ISSUE TITLE
Edit Invoice Page takes too much time to load

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1120]
Edit Invoice Page takes too much time to load

ENV: PROD
Please fix this ASAP

PFA screenshot.

**Comment by sagarnankani** [comment]
![image (27).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1ddbef601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86b4b98a45c2ea3e2de5829d02.png)

**Comment by mustafa-walkover** [comment]
Invoice Renders as soon as i get base64 in response from API
