### ISSUE TITLE
Invoice Template Settings (Note 1 text box issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1129]
While editing settings for an Invoice Template, Note 1 text box is not being displayed sometimes.

ENV: PROD
Please fix this ASAP

**Comment by sagarnankani** [comment]
![image (29).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1ddb0f601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86b5bc8b48c9e1342de78d9d02.png)

**Comment by mustafa-walkover** [comment]
done
