### ISSUE TITLE
Update Ledger (Amount on voucher doesn't get updated)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1140]
If user updates amount in a ledger entry for which a voucher is generated, then amount gets updated for the ledger entry only. Amount doesn't get updated in the voucher.

ENV: PROD
Please fix this ASAP

Resolution:
Update Voucher API should be called everytime user updates a ledger entry.

**Comment by mustafa-walkover** [comment]
API is not working
card no.: 3691 created on waffle board for Update Voucher - Amount issue
card on hold until it is fixed from API

**Comment by mustafa-walkover** [comment]
@sagarnankani @Meghnawalkover closing this card, as this is the task assigned on API
