### ISSUE TITLE
Need to Implement multibranch Reports' APIs

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1145]
Trial Balance, Profit and Loss and Balance Sheet multibranch APIs need to be implemented on UI.

https://docs.google.com/document/d/1rXNQEFvVgpg5EdyvEayCDh0joqdaGv4TlTQP5nkSYIM/edit

https://docs.google.com/document/d/18pNx6lnfBQiN1avziHaj2SEOHNODqRrZtt5C5-tR1jE/edit

https://docs.google.com/document/d/1yGo8YsrKtIs2sDIX7cUbb24UXGruqU4FAWt-3XlSNSg/edit

**Comment by mustafa-walkover** [comment]
@Meghnawalkover please create this card on goodday
