### ISSUE TITLE
Settings module & Onboarding ("Need to display radio buttons for "Inventory Type"")

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1147]
In settings module -> Profile tab and on boarding, Please display 2 radio buttons ("Product" & "Service") for "Inventory Type".

Also, please remove the "Update" button at the bottom of "Profile" page and implement Auto-Update functionality.
When data is being Updated, please show "Saving" text and when it is updated, please show "Saved"

**Comment by mustafa-walkover** [comment]
I have drop mail "Regarding multiple API call for single key `manageInventory`"
