### ISSUE TITLE
Add & Manage (Groups not being displayed in correct place)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1155]
In Add & Manage module, after user deletes a sub group, position of all groups (both fixed groups and sub groups) changes. Sub groups are displayed in the place of Fixed groups and vice versa.
Note: Try deleting sub groups 2-3 times, if the issue is not reproduced in the first attempt.

PFA screenshot.

ENV: PROD
Please fix this ASAP.

**Comment by sagarnankani** [comment]
![grp_pos.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ef868a1c928cbacda5fd53b652fa912a5265296b51a27d20dce27fbd122e590c5d48ac41515a47fdfd8e28f4a42062c80d55b98e30063e937f03a6aa8318b500bf23884984b3bd824fc8e83d37aa.PNG)

**Comment by mustafa-walkover** [comment]
@sagarnankani  I tried to reproduce by deleting 8 sub groups  but unable to reproduce

**Comment by walkover101** [comment]
@sagarnankani pls check I think now we are not facing this type of issue.

**Comment by sagarnankani** [comment]
This is still reproducible on Test and PROD environments.
PFA screenshot.

Steps to Replicate:
1. Create a new sub group in "REVENUE FROM OPERATIONS" group
2. Delete it.
![mustafa.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e58189378385a8cda5fd53b652fa912a5265296b51a27d20dce27fbd122e590c5d48ac41515a47fdfd8e28f4a42062c80d55b98e30063e937f03a6aa8319b500bf248f4883b2bf8244c0ee3c37aa.PNG)

**Comment by rohit-walkover** [comment]
fixed , plz Deploy on test
