### ISSUE TITLE
Ledger - Bulk Voucher Generate (Multicurrency issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1165]
If user sends unique names of two ledger entries in request of any Bulk Voucher Generate API, such that one is a Sales entry (Amount: 100, Converted Amount: 6807) and the other is a Sales return entry (Amount: 222, Converted Amount: 15111.54), then for Sales entry amount value is being considered but for sales return entry, converted amount value is being considered.
This is incorrect. Amount value should be considered for all the entries.

Amount not coming from UI properly that is why this issue is observed.

ENV: PROD
Please fix this ASAP

**Comment by mustafa-walkover** [comment]
not reproducible, tested with sagar sir & mayank sir

**Comment by sagarnankani** [comment]
Checked on Test. This is working fine.

**Comment by sagarnankani** [comment]
Checked on PROD. This is working fine. Hence, closing this card.
