### ISSUE TITLE
Update Ledger (Taxes amount issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1178]
While updating a ledger entry with taxes, sometimes pop up window, asking to update tax transactions' amount, is not displayed. So, tax transactions amount is not updated.
This is incorrect. Pop up window should always be displayed and tax amount should be updated if user clicks on "Yes" button.

ENV: PROD
Please fix this ASAP

**Comment by mustafa-walkover** [comment]
not reproducible

**Comment by sagarnankani** [comment]
Checked on PROD. This is not reproducible on PROD now. Have asked everyone on the channel if anyone is still facing this issue.
We'll close this card if this is not reproducible by anyone.
