### ISSUE TITLE
Trial Balance Export (Missing Loader issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1181]
Loader is not displayed when user exports Trial Balance

ENV: PROD
Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![image (34).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1dcbdf601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00b22a8a4a86b3bc8a45c7e13522e5889d02.png)

**Comment by sagarnankani** [comment]
Loader is not being displayed on ledger page as well. Please fix this ASAP.
ENV: PROD

**Comment by mustafa-walkover** [comment]
please check on test & prod, is working
