### ISSUE TITLE
Dashboard (No API is called on clicking Refresh button in "Ratios" tab)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1182]
On Dashboard, No API is called on clicking Refresh button in "Ratios" tab.

ENV: PROD
Please fix this ASAP

PFA screenshot

**Comment by sagarnankani** [comment]
![ratio.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46fa958e2a8dc1e5cdf9ad4cae58f3806b1c65262852f37271d2e178ea1a7853595f4ea5445b5e40fbfadb39baa47e21d40854b088270a36d43703adb0881eba02bf208a4a81beba8b44c0fa70.PNG)

**Comment by mustafa-walkover** [comment]
done on test, please check
