### ISSUE TITLE
Sign Up (Local Storage issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1199]
Please clear local storage while signing up, in incognito mode.

ENV: PROD
Please fix this ASAP

**Comment by apmeena** [comment]
@sagar, When we open any application in the incognito mode the local storage automatically gets cleared. The data you are talking about is our application's initial data, which we set in the local storage whenever our app get started.

This should not create any problem for any user. Please let me know you still face any issue with this initial data.
