### ISSUE TITLE
Ledger (download voucher issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1208]
On Ledger page or on update ledger pop up window, if voucher is generated for a ledger entry, then a download button is displayed to download the voucher.

When user clicks on this button, download voucher API is called, witth following request body:

{"voucherNumber":["122252"],"voucherType":"payment"}

Value of voucherType is fetched from response of Get all ledgers/get ledger API (voucher -> name). Please fetch the value from newly integrated key "voucherGeneratedType" instead.

Please make sure that this change is deployed on PROD environment together from API and UI end.

**Comment by Eagle-Giddh** [comment]
@sagarnankani please check this card.

**Comment by sagarnankani** [comment]
Checked on PROD. This issue is fixed.
