### ISSUE TITLE
Generate Sales (Group Name field is marked mandatory)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1225]
In Generate Sales module -> Create New Stock side bar, Group Name field is marked as mandatory. This is incorrect.
It should work the same way as it is currently working in Inventory module, i.e.,
If user has not selected any group then by default, stock should be created in Main Group.

ENV: PROD
Please fix this ASAP

PFA screenshot for details.

**Comment by mustafa-walkover** [comment]
Design in under discussion with meghna & shubhendra sir
