### ISSUE TITLE
Ledger Issues

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1234]
1. Ledger date picker is not functioning properly.
2. Value entered by user in Search Text Box disappears.

ENV: PROD
Please fix this ASAP

**Comment by sagarnankani** [comment]
Checked on Test.
1. This is working fine.
2. After searching for a particular query, if user goes to some other ledger and then comes back on the same ledger, same value previously searched by user is passed into API request. Though it is not being displayed in the search text box.

**Comment by mustafa-walkover** [comment]
checked by sheba
