### ISSUE TITLE
New Sales VS Carried Sales Report (Need to display  unique debtors' count on UI)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1235]
New Sales VS Carried Sales Report API: uniqueCount key has been added in response for each type of report in this functionality from API.

Please display the value on UI as well.

**Comment by mustafa-walkover** [comment]
@sagarnankani please test this

**Comment by sagarnankani** [comment]
Checked on Test. This is working fine.
