### ISSUE TITLE
Manufacturing module - Stock details issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1268]
Details of stocks (like Rate, Unit, etc.) are not being displayed while selecting a stock under Source(Consumption) tab.
This is because incorrect group name ("undefined") is being passed in Get stock API URL.

ENV: Test
PFA screenshots.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-09-14 at 11.47.50 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455f76b7191a379ee0c2f56415a4ebc30254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e74455a316336be675306e0a.png)

**Comment by mustafa-walkover** [comment]
checked by sheba
