### ISSUE TITLE
Search Module issues

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1269]
In Search module,

1. Reset button is not being displayed after user enters a query and serches logs
2. Also, if user enters multiple queries and searches for logs, and then clicks on "Filter by account" button again, only 1st query entered by user is being displayed.
Sometimes, 1st query is also not being displayed.

ENV: TEST
Please fix this ASAP so that we can push the code from TEST env to PROD

**Comment by govi2010** [comment]
pr raised #1272

**Comment by govi2010** [comment]
done

**Comment by mustafa-walkover** [comment]
checked by sheba
