### ISSUE TITLE
Inventory Module - "Prev" and "Next" stop working

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1274]
In Inventory module, while viewing a stock group report,
1. Loader stops working before results are displayed
2. After clicking on "Next" button once or twice (to navigate to succeeding pages), both "Next" and "Prev" buttons stop working.

ENV: PROD
Please fix this ASAP

PFA screenshot.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-09-15 at 12.13.16 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455f66b7191a379ed0c2a52415e48bc21254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e7445ca0123060e177306e0a.png)

**Comment by mustafa-walkover** [comment]
Done
