### ISSUE TITLE
Edit Invoice - Incorrect Date Format

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1278]
On Edit Invoice Page, Invoice date and Due Date are being displayed in Incorrect (mm/dd/yyyy) format instead of dd/mm/yyyy format.

ENV: PROD
Please fix this ASAP.

**Comment by sagarnankani** [comment]
PFA screenshot

![edit_inv_date.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ed909337bd8aa799d6bb42b058b2d86b56357c2301a03f32dfa17dbe142b580e581cac44500c46faf98922a3b53d748d5f59ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b9894bc0e83f27e0838b4c3d0c48.PNG)

**Comment by mustafa-walkover** [comment]
Done on TEST

**Comment by Eagle-Giddh** [comment]
Fixed on prod
