### ISSUE TITLE
Inventory In/Out module - Error in console

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1280]
In Inventory In/Out module, when user tries to view a stock in/out report, no API is being called from UI. Also, an error is displayed in console.
PFA screenshot for error.

ENV: PROD
Please fix this ASAP

**Comment by sagarnankani** [comment]
[Uploading Screen Shot 2018-09-15 at 2.19.31 PM (1).png...]

**Comment by sagarnankani** [comment]
Unable to upload screenshot at present.

**Comment by mustafa-walkover** [comment]
checked by sheba
