### ISSUE TITLE
Design suggestions by Meghna

### ISSUE THREAD

**Issue by apmeena** [Walkover-Web-Solution/Giddh-New-Angular4-App#1281]
1. Inventory: By default open report of first stock Group or previous opened stock/group
2. Inventory: On selection of any stock its parent group is also showing highlighted and edit button is coming on both (it should come only on stock)
3. Sales: Selection on customer name box
4: Manage Groups & Accounts: Balance for trigger is not working correctly in create group
5: When I type any number in field 0 should get removed automatically

**Comment by mustafa-walkover** [comment]
added to goodday task
