### ISSUE TITLE
Search Module - Filters getting removed

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1285]

**Comment by sagarnankani** [comment]
In Search Module, If user had applied some filters and searched for a group that has a lot of results, then user gets the results page wise. Now, if user navigates to a different page, let's say page 2, and then again goes back to page 1, then the filters are removed.

ENV: PROD
Please fix this ASAP.

**Comment by govi2010** [comment]
pr raised  #1288

**Comment by govi2010** [comment]
done

**Comment by sagarnankani** [comment]
This issue still persists on PROD. Please fix this ASAP.

**Comment by apmeena** [comment]
That was a different issue. Closing this card.
