### ISSUE TITLE
Invoice Module - Invoice Templates not being displayed

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1293]
In Invoice Module, Templates tab, no Invoice Template is being displayed .

ENV: PROD
Please fix this ASAP

PFA screenshot.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-09-18 at 10.47.03 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455fb6b7191a379ef0c2f56415f4dbc30254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e64f51ad133f64e176356e0a.png)

**Comment by apmeena** [comment]
fixed
