### ISSUE TITLE
Import Module - Next button not working

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1301]
Import Module - Next button is not working

ENV: PROD
Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![image (42).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1dbbbf601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86b1be8d4dc0e03824e5839d02.png)

**Comment by govi2010** [comment]
done and pr raised on test #1330
