### ISSUE TITLE
Update Company - Invalid JSON error

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1332]
Please send empty curly brackets in Request Body of Update Company Patch API, when there is no change in any field.
Currently, empty square brackets are being sent in request body because of which "Invalid JSON" error message is received in response.

//API URL
PATCH http://apitest.giddh.com/company/walkpvindore14504197149880siqli

**Comment by mustafa-walkover** [comment]
done
