### ISSUE TITLE
Download P&L and Balance Sheet APIs - Need to send "from", "to" params instead of "fy"

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1337]
Download P&L and Balance Sheet APIs - Please send "from", "to" params instead of "fy".
"fy" param is removed from both the APIs. It is replaced by "from" and "to" params.

/Current Request URLs: 

Request URL: http://apitest.giddh.com/company/walkpvindore14504197149880siqli/v2/balance-sheet-collapsed-download?fy=

Request URL: 
http://apitest.giddh.com/company/walkpvindore14504197149880siqli/v2/profit-loss-collapsed-download?fy=-1

**Comment by mustafa-walkover** [comment]
@sagarnankani please test this

**Comment by sagarnankani** [comment]
Checked on Test. This is working fine.
