### ISSUE TITLE
Invoice Module - Buttons getting disappeared

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1346]
In Invoice module -> If user clicks on "Generate" button on top, "Preview", "Generate", "Templates" & "Settings" button get disappeared.

ENV: PROD

Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![image (49).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1dbb0f601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86bebf8349c5ed342ce58f9d02.png)
![image (50).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1dab9f601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad03ba2a8a4a86bebf8349c5ef3a23e7829d02.png)

**Comment by govi2010** [comment]
give me some details please

**Comment by mustafa-walkover** [comment]
@govi2010 you can check by selecting generate tab, above 4 tabs(preview, generate, template, settings) will hide. It should be visible

**Comment by govi2010** [comment]
done and #1359 pr raised on production branch

**Comment by mustafa-walkover** [comment]
checked by sheba
