### ISSUE TITLE
Universal Date Picker issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1355]
On Universal Date Picker, If user clicks on any date (other than today's date) twice, then "Custom Range" option gets selected from the menu at the right side of the calendar. However, If user clicks on today's date twice, then "This Financial Year to Date" option gets selected from the menu at the right side of the calendar and dates are passed in API Request accordingly.

This is incorrect. Even when user clicks on today's date twice, "Custom Range" should be selected.

PFA screenshot.
ENV: PROD
Please fix this ASAP

**Comment by sagarnankani** [comment]
![dp.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ec84d86fc093bb80e3ba40b01faad67c4771237005f42920d0bb2bed142b51565a4dad455f5c16eee59b69f7e8682fd70541b8937f5566c7341badbd8117b701b8238d4b80b6bf9801.PNG)

**Comment by mustafa-walkover** [comment]
done & deployed on test, please review

**Comment by mustafa-walkover** [comment]
checked by sheba
