### ISSUE TITLE
Company Import - File not being displayed in Browse field

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1370]
Company Import - When user selects a file, it should be displayed in "Browse" field. Currently, it is not being displayed.

Please collect details from Eagle.

ENV: PROD
Please fix this ASAP.

**Comment by mustafa-walkover** [comment]
done on test y mustafa

**Comment by Eagle-Giddh** [comment]
Export is not working so I can't check this card

**Comment by Eagle-Giddh** [comment]
Fixed
