### ISSUE TITLE
Settings Module - Auto Update and State Code issues

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1371]
In Settings Module - If user enters a few digits in GSTIN field and then takes a pause, Update API is hit automatically, and "Invalid GSTIN" error message is received from API and GSTIN field is cleared.
Resolution: For GSTIN field, do not fire the API unless user enters 15 characters.

Also, State should be selected automatically according to first 2 characters of GSTIN entered by user.

**Comment by mustafa-walkover** [comment]
done on test

**Comment by Eagle-Giddh** [comment]
Fixed
