### ISSUE TITLE
Gmail Integration - Incorrect API being called

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1379]
Gmail Integration - Incorrect API (Request URL: http://apitest.giddh.com/gmail-token) is being called for Get Gmail token.
Please find the New API below.

//New URL:
GET - /company/{companyUniqueName}/gmail-token

ENV: PROD
Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![gmailtoken.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ef999b2a8e97a684ecb101e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00b32a8a4a86bfb98244c6ed3e2cee839d02.PNG)

**Comment by sagarnankani** [comment]
After Integrating a Gmail Account, when user is redirected to Giddh, "Connect With Gmail" button is still displayed instead of "Gmail integrated successfully." message. Only when user reloads the page manually, "Gmail integrated successfully." message is displayed. Please fix this.

**Comment by walkover101** [comment]
Fixed
