### ISSUE TITLE
Update Ledger pop up- Escape Key issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1381]
In any ledger, I double-click to open any entry and then use esc key to close it. Nothing happening on using esc key.

ENV: PROD
Please fix this ASAP

**Comment by mustafa-walkover** [comment]
Done & deployed on Test

**Comment by Eagle-Giddh** [comment]
Working fine

**Comment by Eagle-Giddh** [comment]
working fine on prod
