### ISSUE TITLE
Cmd+K feature

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1382]
Cmd+K feature in giddh: It switches quickly to the new account/ledger, but it shows the data after 7-8 seconds.
Quick switch just changes the name of the account/ledger with the previous data.

ENV: PROD
Please fix this ASAP.

**Comment by mustafa-walkover** [comment]
Done on test

**Comment by Eagle-Giddh** [comment]
not fixed

**Comment by Eagle-Giddh** [comment]
fixed on prod
