### ISSUE TITLE
Data Refresh Issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1385]
Even after switching company, data of previous company is displayed on UI.

ENV: PROD
Please fix this ASAP.

PFA screenshot.

Please note that this issue has been reported multiple times previously. So, make sure this is not reproduced on Prod again.

**Comment by sagarnankani** [comment]
[Uploading Screen Shot 2018-10-16 at 4.03.18 PM.png...]

**Comment by sagarnankani** [comment]
![Screen Shot 2018-10-16 at 4.03.18 PM (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a37cf112284f5e575ecc3c484745e5eb9539e6f4632adf0f4fffdb7f5a25c03d18fdbfd01fba09e9228d4f85bfb9894dc4ef3e77f5979d0d6f405147d4a61760e28b41da59f141e04856ad153e6ae0723474419c0c38.png)

**Comment by mustafa-walkover** [comment]
Please test

**Comment by Eagle-Giddh** [comment]
Fixed
