### ISSUE TITLE
Sales module - Tax issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1386]
If user has an inventory (let's say, fabric) which is linked with a tax, then In "Sales" module, If user selects "fabric" in the first row, then its linked tax is selected in the drop down list automatically, however, if user selects "fabric" again in 2nd row, then tax is not being selected automatically in the drop down list.

ENV: PROD
Please fix this ASAP.

**Comment by Eagle-Giddh** [comment]
Fixed on prod
