### ISSUE TITLE
Taxes - "No GST number found for this company" error

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1390]
In Taxes module, If user selects "GSTR3B" in first drop down, enters email id in Email field and then selects "Email Sheet" from last drop down menu - "No GST number found for this company" error message is displayed. However, GSTIN exists for the company.

PFA screenshots.
ENV: TEST

**Comment by sagarnankani** [comment]
![nogst.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e69b9d3096c1e5cdf9ad4cae58f3806b1c65262852f37271d2e178ea1a7853595f4ea5445b5e40fbfadb39baa47e21d40854b088270a36d43703adbf881eba02b329884d85b0bf8a4bc4fa70.png)
![nogst2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e69b9d3096d1ebc3abaf51ab57f5973d047d317c05f57b2984b42aef1723025d594eac485d5c45f8fe8a79b4aa2e32db025fb28c341521842f1bbeb98515be04b929824c87b6ba894cc7e82f68.PNG)

**Comment by Eagle-Giddh** [comment]
the design has been changed and this working fine
