### ISSUE TITLE
Universal Calendar - Incorrect values being passed in Entry Settings API

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1391]
If user selects "Today" option from Universal Calenda, then Incorrect values ({"fromDate":null,"toDate":null,"duration":1,"period":"MONTH"}
) are being passed in Entry Settings API.
This is incorrect. On selecting today, please provide null values for all the keys in request of  Entry Settings API.

ENV: PROD
Please fix this ASAP

This was fixed previously, but is reproducible on PROD environment again. Please make sure this is not reproducible on Production environment again after it is fixed.

//API Details:
Request URL: http://apitest.giddh.com/company/deleteindia154018683099702mtqw/entry-settings
Request Method: PUT
Status Code: 200 
Request:
{"fromDate":null,"toDate":null,"duration":1,"period":"MONTH"}
Response:
{"status":"success","body":{"noOfTransactions":0,"fromDate":null,"toDate":null,"period":"MONTH","duration":1}}

**Comment by mustafa-walkover** [comment]
done

**Comment by Eagle-Giddh** [comment]
@sagarnankani please check it.

**Comment by sagarnankani** [comment]
Checked on PROD. This is fixed.
