### ISSUE TITLE
send "voucherGeneratedType" in voucher download API

### ISSUE THREAD

**Issue by mustafa-walkover** [Walkover-Web-Solution/Giddh-New-Angular4-App#1403]
http://apitest.giddh.com/company/cashanindia15408877975130o8047/accounts/cash/vouchers/download-file?fileType=base64

replace `voucherType` key to `voucherGeneratedType `

**Comment by mustafa-walkover** [comment]
Done

**Comment by Eagle-Giddh** [comment]
@sagarnankani please check this card

**Comment by sagarnankani** [comment]
This is duplicated by card no. 1208. Hence, closing this.
