### ISSUE TITLE
Manufacturing Module - Incorrect calculation of raw materials' quantity and amount

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1404]
Manufacturing Module - Incorrect calculation of raw materials' quantity and amount

ENV: PROD
Please fix this ASAP

PFA screenshot for details.

**Comment by sagarnankani** [comment]
![eagle1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ed959d2f87d2ebc3abaf51ab57f5973d047d317c05f57b2984b42aef1723025d594eac485d5c45f8fe8a79b4aa2e32db025fb28c341521842f1bbeb98b15be04be20824f81b6b98f4dc3e92f68.png)
![eagle2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ed959d2f87d1ebc3abaf51ab57f5973d047d317c05f57b2984b42aef1723025d594eac485d5c45f8fe8a79b4aa2e32db025fb28c341521842f1bbeb98a15be04be20824f81b6b98f4dc2ed2f68.png)

**Comment by Eagle-Giddh** [comment]
fixed on prod
