### ISSUE TITLE
Sales module - Discount drop down issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1407]
Sales module - In Discount drop down menu, if a discount name is big then user is unable to select the checkbox for it, as its size is very small.

PFA screenshot.
ENV: PROD
Please fix this ASAP.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-10-31 at 5.33.58 PM (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a37df111284f5a575ecc3c484745e5eb9539e6f4632adf0f4fffdb7f5a25c03d18fdbfd01fba09e9228d4f85bfb9894dc4ef3e77f5979d0d6f405147d4a61760e28b41da59f141e04851a41a3e64ef70367e47940c38.png)

**Comment by mustafa-walkover** [comment]
Done on test

**Comment by Eagle-Giddh** [comment]
Fixed
