### ISSUE TITLE
Delete Multiple Ledger - Request Method not supported error

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1414]
"Request Method not supported" error message is received when user tries to Delete multiple ledgers.
This is because new API for Delete multiple ledger is not implemented on UI.

Please check Delete (single) Ledger action also.

Please fix this ASAP
ENV: PROD

PFA screenshot.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-11-03 at 11.55.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f06b7191a379ee0c2e54415b48bc30254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29842c259f34fe04f57a21a3263e77e3f6e0a.png)
![Screen Shot 2018-11-03 at 11.56.07 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f06b7191a379ee0c2e57415f49bc30254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29b4ac259f34fe04f57a21a3265e175366e0a.png)

**Comment by mustafa-walkover** [comment]
its working

**Comment by Eagle-Giddh** [comment]
Yes, working
