### ISSUE TITLE
Login with Google - Window to enter OTP doesn't appear

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1424]
On the Login Page when user clicks on "Login with Google", OTP is sent to user but window to enter OTP doesn't appear.

ENV: PROD
Please fix this ASAP

PFA screenshot.

**Comment by sagarnankani** [comment]
![image (57).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1dabef601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00b32a8a4a81b4be8f4ac6ea3b25e7899d02.png)

**Comment by mustafa-walkover** [comment]
Resolved on test, Please test

**Comment by Eagle-Giddh** [comment]
Fixed on Prod
