### ISSUE TITLE
Invoice Module - Credit Note/Debit Note - mapping issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1431]
In Invoice module, For Credit Note/Debit Note, under Templates tab, while editing a template, "Invoice Date" and "Invoice Number" is being displayed instead of "Voucher Date" and "Voucher Number" respectively and "Voucher Date" should be mapped to "voucherDate" object and "Voucher Number" should be mapped with "voucherNumber" object.
Currently, "Invoice Number" is mapped to Voucher Date.

PFA screenshot.
ENV: TEST

**Comment by sagarnankani** [comment]
![vn.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46fe9ad86fc093bb80e3ba40b01faad67c4771237005f42920d0bb2bed142b51565a4dad455f5c16eee59b69f7e8682fd70541b8937f5566c73a1badbd861db801be238d4981beba9801.PNG)

**Comment by Eagle-Giddh** [comment]
Fixed on prod
