### ISSUE TITLE
Sales Module - Stock transaction issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1432]
In Sales module, even when user selects a sales account with stock, only Sales ledger entry is created without stock.

This is because stock details are not being provided in request.

PFA screenshot.

ENV: PROD
Please fix this ASAP

**Comment by sagarnankani** [comment]
![Untitled2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46dd9a8e2a968fac8bbbfd0fe64de29b234324676b5ee17e71d3b371be1579515a571dae47585f4df9fa882fa1b56e62964e49bc8f3900299f7744eeaa880dbe06b0218e4b87b1bc8f4cc6e03c21e099c2.png)

**Comment by mustafa-walkover** [comment]
Not getting stock in the response of GET account.

Here is the API detail


Request URL: https://api.giddh.com/v2/company/cottonindore15426954000130rdgko/accounts/sales
Request Method: GET


{
	"status": "success",
	"body": {
		"tagNames": [],
		"createdBy": {
			"name": "prachee nitnware",
			"email": "prachee.2892@gmail.com",
			"uniqueName": "prachee.2892@gmail.com",
			"mobileNo": "917470557772"
		},
		"email": null,
		"mobileNo": null,
		"addresses": [],
		"city": null,
		"pincode": null,
		"companyName": null,
		"sacNumber": null,
		"hsnNumber": null,
		"attentionTo": null,
		"emails": [],
		"openingBalanceType": "DEBIT",
		"closingBalanceTriggerAmountType": null,
		"openingBalance": 0.0000,
		"openingBalanceDate": "01-04-2018",
		"closingBalanceTriggerAmount": null,
		"foreignOpeningBalance": 0.0000,
		"discounts": [],
		"applicableTaxes": [{
			"uniqueName": "gst5",
			"name": "GST@5%"
		}],
		"isFixed": false,
		"yodleeAdded": true,
		"accountType": "Revenue",
		"successMessageForBankDetails": null,
		"errorMessageForBankDetails": null,
		"accountBankDetails": [],
		"uniqueName": "sales",
		"country": {
			"countryName": "India",
			"countryCode": "IN"
		},
		"createdAt": "20-11-2018 06:30:00",
		"updatedAt": "21-11-2018 05:34:44",
		"updatedBy": {
			"name": "prachee nitnware",
			"email": "prachee.2892@gmail.com",
			"uniqueName": "prachee.2892@gmail.com",
			"mobileNo": "917470557772"
		},
		"stocks": null,
		"rowNumber": null,
		"mergedAccounts": "",
		"cashFreeVirtualAccountData": {
			"virtualAccountNumber": null,
			"ifscCode": null,
			"name": null
		},
		"parentGroups": [{
			"uniqueName": "revenuefromoperations",
			"name": "Revenue From Operations"
		}, {
			"uniqueName": "sales",
			"name": "Sales"
		}],
		"successMessageForCashFreeVirtualAccount": null,
		"errorMessageForCashFreeVirtualAccount": null,
		"currency": null,
		"description": null,
		"name": "Sales"
	}
}

**Comment by mustafa-walkover** [comment]
@sagarnankani Issue resolved, please test

**Comment by sagarnankani** [comment]
Checked on Test, this is fixed.

**Comment by sagarnankani** [comment]
Checked on PROD. This is working fine.
