### ISSUE TITLE
Journal Voucher - Sales transaction issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1433]
In Journal Voucher module, under "Sales" "as Voucher" tab when user selects a Debtor account in "Party A/C Name" field and a Sales Account and then selects CGST and SGST accounts, enters value for the same and then goes ahead and Saves it, a ledger entry is created consisting only CGST and SGST accounts without Sales transaction.
This is because Sales account details are not being provided in request.

ENV: PROD
Please fix this ASAP

PFA screenshot.

**Comment by mustafa-walkover** [comment]
Please test this case on Test, @apmeena has resolved all the issues reported to him in JV

**Comment by Eagle-Giddh** [comment]
Not fixed.
check image for reference.
![Screenshot 2018-12-14 at 11.08.41 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c078f1798e7720011e7d8c9/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7850e32a64c5b279f112234f5b5e5edd3c4a4356bcbbd671f3e57862804e0ebcd76d5625c16f11a9b0d11db901ba298e4c84b2bb891ed2f42f67b6d5db1063474f4dcbed5727a19041c95df24fe64b53a413316ae3732431.png)
