### ISSUE TITLE
Import module - Unable to Import Inventory

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1438]
In Import module, when user uploads a xls file and then clicks on "Next" button, nothing happens. Next screen is not displayed and user is unable to import inventory.

ENV: PROD
Please fix this ASP

PFA screenshot.

**Comment by sagarnankani** [comment]
![INVENTORY IMPORT ERROR.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46c1baac06acb786bdd0ff6a896ddfa61d0602411b2b91693cc7f33ab0487e021b4d44be44095944f5a88e79a6b33423885a0bedd8685c75c23a12feaa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4b3d1c0c1f8ffe5836a69c5985.PNG)

**Comment by walkover101** [comment]
@sagarnankani pls update and move accordingly.

**Comment by mustafa-walkover** [comment]
@sagarnankani `closing this card as not on UI`, I showed this is happening in import account due to wrong mapping in response.


I have shared the details for the same on slack.

`For more info, please import account`
