### ISSUE TITLE
GST Filing Module - "Generate Purchase" module opens up

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1446]
In "GST Filing" module, under GSTR2 tab, when user clicks on "Recocilation" then "Generate Purchase" module opens up. This is incorrect.
GSTR2 Details should be displayed instead.

ENV: TEST

**Comment by sagarnankani** [comment]
Closing this card as this is requirement. Purchase module will open up if there are no purchase entries in company and user clicks on "Reconcilation".

**Comment by walkover101** [comment]
@mustafa-walkover & @sagarnankani Reconcile should work in all cases. It doesn't depend on purchase entries in giddh.

**Comment by walkover101** [comment]
When I click on any tab under GST reconcile it is showing me an error message "Authentication detail is not found please try for OTP " This could be shown when user click for GST reconcile details.
