### ISSUE TITLE
Reports Module (Trial Balance) - Trial Balance itself opens up on double click

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1460]
In Reports module, while viewing Trial Balance, if user clicks on a particular group then all its accounts are displayed. Now, if user double clicks on any account name, then ideally its ledger should open up. However, this is not the case. Trial Balance itself opens up in a new tab on double click.

However, on this newly opened Trial Balance page, if user double clicks on an account name, its ledger opens up successfully.

This is how it should work the first time itself.

ENV: PROD
Please fix this ASAP.

**Comment by Eagle-Giddh** [comment]
Fixed on Prod
