### ISSUE TITLE
Sales Module & Invoice Module (Generate/Update Voucher) - "Invalid Date" issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1462]
1. While generating a new invoice from "Sales" module or while Updating an invoice from "Invoice" module, if user enters an invalid value in Shipping Date field, then it is replaced by "Invalid Value" and the same text "Invalid Value" is passed in API request.
This is incorrect. If user enters Invalid Date, then please mark the field red and display "Invalid Date" message below the field. Also, deactivate "Generate Voucher"/"Update Voucher" buttons.

2. Please check all other Date fields as well and implement the same validation in all the fields if same issue occurs for other fields as well.

3. Even when user enters a valid date (using keyboard and not the date picker) in Shipping Date field, it is replaced by "Invalid Date".

ENV: PROD
Please fix these issues ASAP.

PFA screenshots.

**Comment by Eagle-Giddh** [comment]
I have tested this, it is working fine

**Comment by Eagle-Giddh** [comment]
fixed on prod
