### ISSUE TITLE
New vs Old Invoices module - Incorrect values issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1464]
Incorrect values are displayed for "Clients", "Amount" and "No. of invoices" in New vs Old Invoices module.

ENV: PROD
Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![Screenshot 2018-12-01 at 5.50.31 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7955e32a64c5b666ea1235525e4f2ed153444d04bea6d37ef5f22e7a98595aebd1640e73943d14a4eb8019bf01b325884e81b1bfd85edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cf54de74a56a314346ae6647b.png)

**Comment by Eagle-Giddh** [comment]
fixed

**Comment by Eagle-Giddh** [comment]
It is working wrong

**Comment by mustafa-walkover** [comment]
@Eagle-Giddh done & deployed on test

**Comment by mustafa-walkover** [comment]
@Eagle-Giddh please share the details with me
