### ISSUE TITLE
Invoice Templates - Notes (mapping) issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1466]
Invoice template content > In case of new company notes is not working.

Reason: notes and other fields of footer are wrongly mapped with the request body of update template api and that's why notes is not getting updated over invoice.
So please make the necessary changes.

ENV: Test, PROD
Please fix this ASAP

**Comment by mustafa-walkover** [comment]
It Will be fix once new template json deployed on prod, please test new template Json
