### ISSUE TITLE
Setting -> Profile Auto Save GST No

### ISSUE THREAD

**Issue by walkover101** [Walkover-Web-Solution/Giddh-New-Angular4-App#1498]
It is giving error and removing all enter data when I am trying to add GSTIN. Before to update manually it is throwing error.

**Comment by walkover101** [comment]
[Uploading Screen Shot 2018-12-11 at 12.22.21 PM.png...]

**Comment by Eagle-Giddh** [comment]
not fixed

**Comment by Eagle-Giddh** [comment]
fixed on prod
