### ISSUE TITLE
Preview/Download Invoice - Notes font issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1504]
On previewing or downloading a generated invoice, font size and style of the notes text on invoice are incorrect.

PFA screenshot.

ENV: PROD
Please fix this ASAP.

**Comment by sagarnankani** [comment]
![Screenshot 2018-12-12 at 10.27.35 AM (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7856e32a64c5b278f1102c4f5c5a5edd3c484745e5eb9539e6f4632adf0f4fffdb7f5a25c03d18fdbfd01fba09e9228d4f85bfb9894dc4ef3e77f5979d0d6f405147d4a61760e28b41da59ff41e04851a0163f62ee7f367d47930c38.png)

**Comment by mustafa-walkover** [comment]
please test, done by sadiq on API html

**Comment by walkover101** [comment]
Fixed
