### ISSUE TITLE
Company Name issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1517]
After creating a company, if user edits the company name, then the updated name should be displayed in menu bar on top left corner.
Currently, previous company name is displayed even after refreshing the page.

PFA screenshot.
ENV: Test

**Comment by sagarnankani** [comment]
![bc.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ea97d86fc093bb80e3ba40b01faad67c4771237005f42920d0bb2bed142b51565a4dad455f5c16eee59b69f7e8682fd70541b8937f5566c7351badbd861bb806be268f4e8db3b99801.PNG)

**Comment by walkover101** [comment]
It is done.
