### ISSUE TITLE
Template Invoice module - Note 1 issues

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1525]
Template Invoice module - Note 1 issues:
1. "*Tax to be paid on Reverse Charge" is displayed twice.
2. <br> is being displayed instead of displaying text after <br> in a new line.

ENV: PROD
Please fix these issues ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![ms.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e587d86fc093bb80e3ba40b01faad67c4771237005f42920d0bb2bed142b51565a4dad455f5c16eee59b69f7e8682fd70541b8937f5566c7341badbd861abe08bf20834f80b1bc9801.PNG)

**Comment by mustafa-walkover** [comment]
Done, please test

**Comment by walkover101** [comment]
@mustafa-walkover & @Meghnawalkover please make it confirm first this default content should be shown or not on generated invoice then move it for live.
