### ISSUE TITLE
Invoice Module - Get all Ledgers API is being called unnecessarily

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1532]
Invoice Module - Get all Ledgers API (Request URL: http://apitest.giddh.com/company/discacindone15446788995780sbgga/ledgers?from=21-11-2018&to=21-12-2018&page=1&count=12&voucherType=sales
Request Method: POST
Status Code: 404 ) is being called unnecessarily on "Preview" page. It should be called only on "Generate" tab.

ENV: PROD
Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![Screenshot 2018-12-21 at 12.34.16 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7b55e32a64c5b27af1112f4f5e595ecc3c4a4356bcbbd671f3e57862804e0ebcd76d5625c16f11a9b0d11db901ba298e4c84b2bb891ed2f42f67b6d5db1063474f4dcbed5727a19041c95df24ee24454a7133360e0762431.png)

**Comment by mustafa-walkover** [comment]
done, please test

**Comment by walkover101** [comment]
Done.
