### ISSUE TITLE
Case sensitive issue on URL

### ISSUE THREAD

**Issue by walkover101** [Walkover-Web-Solution/Giddh-New-Angular4-App#1536]
All page should be open if user open url on capital or small latter. 
It should not be case sensitive. Currently getting 404 for the following page https://giddh.com/inventory-management-software.php

**Comment by mustafa-walkover** [comment]
@sagarnankani please check, it should be done on server side

**Comment by mustafa-walkover** [comment]
@walkover101 done on test, please check
