### ISSUE TITLE
Linked Bank account

### ISSUE THREAD

**Issue by Meghnawalkover** [Walkover-Web-Solution/Giddh-New-Angular4-App#1546]

**Comment by Meghnawalkover** [comment]
1. By default show today's date.
2. scroll in list of listed banks

**Comment by Meghnawalkover** [comment]
![Group 173.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bd1642b3dfe740013eebf3c/125516c66e82c728ace21e0d46cf86953692c3f8d8bafd0fe64de29b234324676b5ee17e71d3b371be1579515a571dae47585f4df9fa882fa1b56e62964e49bc8f3900299f7744eeaa880dbe06b0218e4b80bfb5824fc0ea3421ee99c2.png)

By default show today's date and user can change it

**Comment by Meghnawalkover** [comment]
![Image 2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bd1642b3dfe740013eebf3c/125516c66e82c728ace21e0d46c1999b2487c3fbcda5fd53b652fa912a5265296b51a27d20dce27fbd122e590c5d48ac41515a47fdfd8e28f4a42062c80d55b98e30063e937f03a6aa8318b500bf248e468cbeb88b4fc5e13a37aa.png)

Scroll in list of listed banks

**Comment by Meghnawalkover** [comment]
![Image 1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bd1642b3dfe740013eebf3c/125516c66e82c728ace21e0d46c1999b2487c3f8cda5fd53b652fa912a5265296b51a27d20dce27fbd122e590c5d48ac41515a47fdfd8e28f4a42062c80d55b98e30063e937f03a6aa8317b500bf248e468cbfb8824ec4ef3b37aa.png)

After submitting credential sometimes user has to close the model manually and then has to reload to get data. (in some computer its working properly but in some its not)

**Comment by mustafa-walkover** [comment]
@Meghnawalkover  if a user gets the result as failed or success, popup window closed automatically, it remains open till the status is "IN_PROGRESS"

**Comment by Meghnawalkover** [comment]
@mustafa-walkover yeah this process is working correctly in few systems and the mentioned bug is coming in few
