### ISSUE TITLE
Invoice Table issue

### ISSUE THREAD

**Issue by Meghnawalkover** [Walkover-Web-Solution/Giddh-New-Angular4-App#1547]
when HSN/SAC column is blank further column's value shifting in left.
HSN/SAC value not coming though it is checked in settings

on PROD

**Comment by Meghnawalkover** [comment]
https://downloads.intercomcdn.com/i/o/93781848/4f0e307327554da1dd06b75c/Screenshot+2018-12-30+at+11.24.17+PM.png 

error

**Comment by mustafa-walkover** [comment]
goodday API card #473
