### ISSUE TITLE
Template Invoice module (Settings tab) - Invalid email error

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1548]
Invalid email error is received when user enters an email in "From email" text box in Template Invoice module (Settings tab) such that the domain in the email id is a private domain. For example, sagar@abcd.social.
Please fix this ASAP.
ENV: PROD

PFA screenshot.

You can use the same Regex that is being used at backend:
`[a-z0-9!#$%&'*+\=?^_`{|}~-]+(?:\.[a-z0-9!#$%&’*+\=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?`

**Comment by sagarnankani** [comment]
![invalidemail.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e19a8c228e8aad8ae4be4aa81fbcd6395428792c07b7692ac7b629e9122200580d4ea9490b5d42fcf9802ea5b73877890e19f1c32f0e2a92624cf5f2d75dad0ba821834584b3b88c4ec3ee3d25e182894b2c53.png)

**Comment by Meghnawalkover** [comment]
15 mins
