### ISSUE TITLE
Login - "Internet Disconnected. Please check your internet connection."

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1553]
"Internet Disconnected. Please check your internet connection." error message is displayed when user tries to login. User is properly connected to internet and he is able to use other applications like anydesk.

ENV: PROD
Please fix this ASAP

**Comment by mustafa-walkover** [comment]
shubhendra sir suggested to remove script given by him, removed on test. Please test on the client PC
