### ISSUE TITLE
Ledger - B/F balance is not being displayed

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1578]
Ledger - B/F balance is not being displayed, even when it is being provided in API response.

PFA screenshot.

ENV: PROD
Please fix this ASAP

**Comment by sagarnankani** [comment]
![Pasted_image_at_2019-01-04__10_53_AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46d895893787879686e4be44a162f180161477227049f37a3dd5b71780132b3e5a5c21dd3c4a4356bcbbd671f3e57862804e0ebcd76d5625c16f11a9b0d11db901ba298e4c84b2bb891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df24de44a5cad173263e6732431.png)

**Comment by mustafa-walkover** [comment]
@sagarnankani please test
