### ISSUE TITLE
Filter - Invoice Generate

### ISSUE THREAD

**Issue by Meghnawalkover** [Walkover-Web-Solution/Giddh-New-Angular4-App#1591]
Filter is not working in generate.. account and date filter

**Comment by mustafa-walkover** [comment]
@sagarnankani please check, checked by me. Request payload is correct but getting incorrect  response sometimes. 

please Test, let me know if anything needed on UI.
Thanks

**Comment by mustafa-walkover** [comment]
@walkover101 please test on test. Reported by sheba
