### ISSUE TITLE
Sales Invoice module - Qty, Unit, Rate fields disabled issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1599]
In Sales Invoice module, when user selects such a stock in Product/Service drop down that does not has unit rate details, then Qty, Unit, Rate fields are disabled. This is incorrect.

Even when user hasn't provided unit rate details, these fields should be enabled so that user can provide values in these fields on run time.

Note: stock's base unit should be displayed in Unit drop down by default.

Please fix this ASAP
ENV: PROD

PFA screenshot.

**Comment by sagarnankani** [comment]
![Screen Shot 2019-01-07 at 12.58.45 PM (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226454f46b7191a379ed0c2e59415b4bbc21254f5cfde09b37b4f67e2fd00958a9c3674d71973b11a5e9854dbf04b273894985b6b58f4fc1ec3a26b599935d7c4f5b4cd6a2047ff5db59c24af44beb4c50a0153e67ee77377c4f96186761.png)

**Comment by mustafa-walkover** [comment]
@sagarnankani Done, please test

**Comment by Eagle-Giddh** [comment]
Working fine on test
