### ISSUE TITLE
Update Ledger - ledger balances not getting updated issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1603]
The ledger balances are not getting updated in real time, but after refreshing the page. Plz check..

ENV: PROD
Please fix this ASAP

PFA screenshot

**Comment by sagarnankani** [comment]
![Screenshot 2019-01-08 at 11.53.31 AM (2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416763e795ce32a64c5b279f117284f5c5e5edd3c484746e5eb9539e6f4632adf0f4fffdb7f5a25c03d18fdbfd01fba09e9228d4f85bfb9894dc4ef3e77f5979d0d6f405147d4a61760e28b41da59f141e04851a21a3563e471347a42900c38.png)

**Comment by mustafa-walkover** [comment]
@sagarnankani done, please test

**Comment by Eagle-Giddh** [comment]
working fine on test
