### ISSUE TITLE
Search Module - Blank page issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1604]
A Blank page is displayed when user navigates to Serach module.

ENV: PROD
Please fix this ASAP

PFA screenshot

**Comment by sagarnankani** [comment]
![image (83).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1d7baf601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad03ba2a8a4a81b0b5894cc9ea3527ef829d02.png)

**Comment by mustafa-walkover** [comment]
Done on test, Please test

**Comment by sagarnankani** [comment]
Checked on Test. This is working fine. Please push this on PROD env ASAP.
