### ISSUE TITLE
Ledger and Sales Invoice module - stock uniquename issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1606]
1. In ledger module, before saving a ledger and on double clicking on ledger (2nd time onwards), stock uniquename is being displayed in brackets next to particulars, instead of stock name.
2. When user double clicks on a ledger first time, no transaction is displayed in pop up.
3. Even in sales module, if user selects a stock in Product/Service drop down and then removes focus, stock uniquename is displayed in brackets instead of name.

PFA screenshots.

ENV: PROD
Please fix this ASAP

**Comment by sagarnankani** [comment]
![image (88).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1d7b1f601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad03ba2a8a4a81b0b58945c0ee3f2de0839d02.png)
![image (87).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1d7bef601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a81b0b58945c0ef3d24e1839d02.png)
![image (86).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1d7bff601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a81b0b58945c0e03f26e68c9d02.png)

**Comment by mustafa-walkover** [comment]
Done & deployed on test, @sagarnankani please test on test server and let me know, so can deploy it on live.
