### ISSUE TITLE
Ledger - Advance Search - Incorrect closing balance value

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1607]
Ledger - Advance Search - After applying filters in Advance Search and searching transactions, closing balance values are not updated.

Resolution: Whenever merge API is called, please update closing values provided in merge API's response.
And whenever, giddh-ledger API is called, call the balance API separately and display the balance as per this API's response.

ENV: PROD
Please fix this ASAP

**Comment by mustafa-walkover** [comment]
done on test, please test
