### ISSUE TITLE
Download Voucher - Incorrect values issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1609]
Download Voucher - Incorrect values are displayed in Hsn/Sac, Taxable Value, IGST, Total fields on Invoice.

PFA.

ENV: PROD
Please fix this ASAP

**Comment by sagarnankani** [comment]
[onlinehr team  - 20181220-9 (1).pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e79a962a8c86a19da9ab46a550b0d464067523785cf27922d5ae71ff0a2a484d435cec03070511afbd9b21b4b36d768a555aea836d5a7c953f17acb88b1abc00be27881d97aaaec81d9ebc6278bec1da0d2c1417198ef55c30a49f42cd59f54fe74553a0017b.pdf)
[download (23).pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ec9b8d2d8e8ca88ba9f711f714b2d86b56357c2301a03f32dfa17dbe142b580e581cac44500c46faf98922a3b53d748d5f59ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98e4ac9ed3c26e28b8e4f390c48.pdf)

**Comment by mustafa-walkover** [comment]
@sagarnankani aditya is working on it

**Comment by mustafa-walkover** [comment]
@sagarnankani closing this card, it is fixed by aditya & deployed on prod
