### ISSUE TITLE
Template Invoice module - Credit Note page- vouchers are not being displayed

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1620]
In "Template Invoice" module, on "Credit Note" page, credit note vouchers are not being displayed even when credit notes exist in the company for the given date range. This is because incorrect parameter (type) is being passed in URL instead of "voucherType".

Please fix this for all voucher types.

ENV: TEST

PFA screenshot.

**Comment by sagarnankani** [comment]
![cn.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46eb9ad86fc093bb80e3ba40b01faad67c4771237005f42920d0bb2bed142b51565a4dad455f5c16eee59b69f7e8682fd70541b8937f5566c7351badbd8618be09b921894f82beb99801.PNG)

**Comment by mustafa-walkover** [comment]
@sagarnankani @Meghnawalkover  it is still working with same param(type).

Request you to please check again
