### ISSUE TITLE
Ledger Issues

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1621]
1. Scroll bar is not present on ledger.
2. Amounts of some transactions (in case of compound ledger) are not being displayed.
3. giddh-ledger API is being called multiple times.
4. Unable to apply taxes manually on update ledger.

**Comment by mustafa-walkover** [comment]
1, 2, 4 resolve and deployed on test, please test @sagarnankani
