### ISSUE TITLE
Manage Groups & Accounts - uniquename issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1622]
On "Manage Groups & Accounts" page, while trying to create an account or a group, unique name is not being generated according to the name provided for account/group by user and hence, Account with uniquename already exists error message is displayed and user is unable to create account/group.

ENV: TEST

**Comment by mustafa-walkover** [comment]
Checked by myself, not reproducible.. It was due to some other error
