### ISSUE TITLE
Inventory Bug List

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#394]
1- In Create Custom Stock Unit sidebar: Divide symbol between "parent unit" & "quantity per unit" fields is missing - done

2- Under "Unit Name" column, Name and Code of different units is displayed. As per design, code should be inside brackets. Brackets are missing. - done

3- "Unit Name" and "Parent Unit" fields don't get cleared on clicking "Clear" button - done

4- On clearing "Unit Name" field, "Unit Code" field should also get cleared. - done
"Unit Name" and "Parent Unit" fields should also get cleared when a new stock unit is created - done

5- While creating/modifying a Stock Group: Special characters are being allowed in stock group uniquename field - While modifying a Stock Group when user enters Special characters that are not allowed in unique name field and then clicks on "Update" button, loader on "Update" button doesn't stop, even after unique name is updated. - done

6- "Parent Group" field should get cleared when user unchecks "Is it a sub group?". Also, "Parent Group" field should get cleared after a new stock group is created -  Even after unchecking "Is it a sub group?", value previously selected by user goes in "uniqueName" param of "parentStockGroup" object.
Also, after this, if user attempts to creates a new group and doesn't check on "Is it a sub group?" link & directly clicks on "Save" button, then value previously selected by user goes in "uniqueName" param of "parentStockGroup" object. - Value of "isSubGroup" should either be true or false. Currently, If user attempts to creates a new group and doesn't check on "Is it a sub group?" link & directly clicks on "Save" button, then value of "isSubGroup" is null. - done

7- While creating/updating a Stock Account: 
No validation on HSN code field. - Please allow blank spaces also in HSN field. Please remove validation of minimum 10 digits on HSN field. - While creating Stock, If user enters only 2 digits in "HSN Code" and clicks on "Save", then HSN Code doesn't get saved. - This issue still persists. - done

8- Even when all the mandatory fields are filled in, "Save" button is disabled (to replicate - fill in all the fields then enter a long value in HSN field and then clear it) - done

9- By default, both "purchase" and "sales" account details should be unchecked - done
Rate field in second row is disabled always - done

10- In second row when user clicks on "+" button, new row is not added (unit/rate) - done

11- "+ Add new" option is not available in "parent group" and "unit" drop down lists - done,
 suggestion: After user has created a new stock group or unit, it should get selected in "parent group" /"unit" field respectively.
Also, Sidebar should close automatically once user has created a new stock group or unit.

12- Stock qty and unit drop down lists have interchanged - Stock Quantity field should be displayed before Stock Unit - done

13- After clicking on "Add" button, same stock name as that of row 1 gets selected in row 2. This is incorrect. It should be empty. - done

14- Only stock unit code is displayed once we have added it - done

15- "Add" button is not working in 2nd row (finished good) - "Add" button should not be clickable if 
Input Stock Name, Stock Unit & Stock Quantity fields are not filled. - Error message appears if all fields are not filled - done

16- Once user edits a row and updates it, values are displayed in "input stock name", "stock qty"  fields, however these values are not selected (notice that the cross sign is not displayed) and then when user clicks on "Add", "All Fields Are Required To Add Item" error is displayed. - done

17- After editing a raw material of an already created finished stock, is user selects a value from "stock quantity" field and then selects another value from "Input stock name" field, then "stock quantity" field value gets deselected again. - If user adds a raw material in an already created finished stock, then after getting response from API, 4 blank rows are added for adding raw material. And 4 objects are initialised in API request body. Hence, "message":"No stock found with uniquename "" message is received in API response.
Also, while creating a new finished stock account, linked stocks selected by user are not being passed in API request body. PFA screenshot.
>>As soon as user user adds a raw material and clicks on update, newly added raw material disappears and a blank row is added. - done

18- Purchase Account details, Sales Account details, "Stock unit" & "Select parent group" fields don't get cleared on clicking cancel/save buttons - done

Suggestions:
Maximum character limit should be set for all the fields
After deleting the unit and rate provided in 2nd row, both delete and add buttons should be available in first row. Currently, only "+" button is displayed.

Bugs/Suggestions reported by Sheeba:

Suggestion:
After creating group pop-up window should be closed

Bug:
19- On clearing "Open. Qty" & "Amount" fields, "Rate/Stock Unit" field should also get cleared - done

**Comment by mustafa-walkover** [comment]
7- NO API implementation needed, discussed with alok sir.

**Comment by sagarnankani** [comment]
![mustafa](https://user-images.githubusercontent.com/30191516/35682164-b6bde8a4-0785-11e8-834f-c4e3f74bbcce.png)

**Comment by mustafa-walkover** [comment]
for suggestions, please talk to alok sir
