### ISSUE TITLE
Data not getting refreshed

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#396]
Data is not getting refreshed automatically. User has to manually refresh the page.
This issue occurs across the complete Application.

For example, Open "Cash" Account of any company and then create a new company or switch company, data doesn't get refreshed automatically. 

Please fix this ASAP as this is a PROD issue.

Env:  Test, Prod

**Comment by govi2010** [comment]
Please let me know the specific case. because I can not see such things happening

**Comment by sagarnankani** [comment]
Whenever new user signs up and creates a new company, a blank page appears. This issue occurs because data is not getting refreshed.
User needs to refresh the page manually. 
This is just one of the many scenarios.

This card is related to card no. 697.

**Comment by sagarnankani** [comment]
Please fix this on highest priority.
