### ISSUE TITLE
Create Account/Update Account form ("Mobile Number" field placeholder)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#403]
IN "Manage Groups & Accounts" module, in Create Account/Update Account form, place holder for "Mobile Number" field is displayed as "9198XXXXXXXX".
Please remove 91 from place holder as "+91" is already displayed before the field.
PFA screenshot.

**Comment by sagarnankani** [comment]
[Uploading mobile.png...]

**Comment by sagarnankani** [comment]
![mobile.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e59b982a8e86ebc3abaf51ab57f5973d047d317c05f57b2984b42aef1723025d594eac485d5c45f8fe8a79b4aa2e32db025fb28c341521842f1bbeb98515be04bb27834e80beba8d4bc0e02f68.png)

**Comment by apmeena** [comment]
Done
