### ISSUE TITLE
Company Settings (Unable to set state code without GSTIN)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#435]
In Company "Settings" module, user is unable to set state code without GSTIN.
ENV: PROD
Please fix this at the earliest.

**Comment by mustafa-walkover** [comment]
ISSUE IN API:

1: while saving only stateCode in company Profile (GST Number Array), giving an error `Following Constraints failed : Gst number should contain only 15 digits.`
2. GST address/stateCode should update without GSTIN number.

**Comment by apmeena** [comment]
Please remove this validation from API side.
