### ISSUE TITLE
Preview & Generate Invoice Bug List

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#467]
1. Numbers & Special characters (except spaces, hyphens and dots) shouldn't be allowed in Attention To field
2. For Invoice Date field, all dates prior to latest entry date should not be pickable.
3. Invoice Number field should not be displayed
4. Please rectify billingState label
5. State drop down should be available for both Shipping State & Billing State
5. In Due Date field, if user types in 02-01-2018, then the date changes to 01/02/2018. Note: This issue occurs intermittently.
6. No validations are put on GSTIN and State Code fields (for both Billing & Shipping addresses)

**Comment by apmeena** [comment]
We are working on a new design of this module so this card is on hold for now.
