### ISSUE TITLE
Add & Manage (Move account issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#481]
In "Add & Manage" module, if user creates a new group and then selects an account  and clicks on "Move to Group" field, newly created group is not found in the drop down list.
If user refreshes the page, then it works.
However, again if user tries to move another account in newly created group, same issue occurs.
ENV: PROD
Please fix this on highest priority as this is a PROD issue.

**Comment by apmeena** [comment]
Done.
