### ISSUE TITLE
Inventory Report (Incorrect Date Range is displayed)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#517]
In "Inventory" module, Incorrect Date Range is displayed in Date Picker Field, while viewing Inventory Report. Please display correct date range, which is being passed in API URL.

PFA screenshot.

**Comment by sagarnankani** [comment]
![inventory.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e19a8c268c97a69df0fd0fe64de29b234324676b5ee17e71d3b371be1579515a571dae47585f4df9fa882fa1b56e62964e49bc8f3900299f7744eeaa880dbe06b0218e4d85b4b88d4ec7eb3b22e599c2.png)

**Comment by sagarnankani** [comment]
This issue still persists.

Steps to Replicate:
1. Select a Universal Date Range (eg. 4 apr - 7 apr)
2. In "Inventory" module, click on any stock group to view its report. Change the Date Range (in Date Picker field above the report) to 7 mar - 24 mar.
3. Click on any other stock group.

PFA screenshot.
[Uploading date_inv.png...]

**Comment by sagarnankani** [comment]
![date_inv.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ec958e26bd8aa799abf301b44fff9e2c4533317346f62a26d5ba29e8402b54570c4caa41585641fff88d2ca5e42e6c981e5ab38532022d8c6853beb2901eb60bbb25894b85b2b58f49c7ef3423f5c6.png)

**Comment by sagarnankani** [comment]
Same date range is being passed in API URL as that displayed in date picker.
This is correct.

However, when user comes to Inventory module, Date Range selected in universal date field should be displayed date picker and the same date range should also be passed in API url.

**Comment by mustafa-walkover** [comment]
checked by sagar
