### ISSUE TITLE
Get all ledgers ("Refresh" issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#546]
Everytime a user selects a date range on date filter and clicks on "Go" button, please call get all ledgers API (even if date range is same as previous).

//API Details:
Request URL:http://apitest.giddh.com/company/newsncindore15000172022770ygv88/accounts/mergecash/ledgers/transactions?count=15&from=08-02-2018&page=0&q=&reversePage=false&sort=asc&to=08-02-2018
Request Method:GET
Status Code:200 OK

**Comment by mustafa-walkover** [comment]
fixed on prod
