### ISSUE TITLE
Ledger Advance Search (Pagination issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#566]
If user filters ledger data using "Advance Search" option, then pagination of ledger fails to function normally.

PFA screenshot.

ENV: PROD

**Comment by sagarnankani** [comment]
![adv_pag.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e9908c1c9282aecda5fd53b652fa912a5265296b51a27d20dce27fbd122e590c5d48ac41515a47fdfd8e28f4a42062c80d55b98e30063e937f03a6aa8318b500bf228b4687b4b58b4fc0eb3537aa.png)

**Comment by mustafa-walkover** [comment]
fixed
