### ISSUE TITLE
Add & Manage (groups position interchange)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#586]
On deleting a sub group, position of all he fixed groups and sub groups interchange.

PFA screenshot for details.

**Comment by sagarnankani** [comment]
![grps_positions.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ef868a30bd93a69ce0ab4aab53e3d665043761260ea62864c7b96aea432d51560e49fe415d5717feff892bafb33f718e5b08bfc3714d36976345f3e5db55ea43a82a994e8dbcbd8f4ec1e93d2ce4828f4d3c161755.png)

**Comment by sagarnankani** [comment]
*position of all the...

**Comment by govi2010** [comment]
not reproducible
