### ISSUE TITLE
"Pay Now" Button not working

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#588]
Wheen user clicks on "View Invoice & Pay Now" link on invoice email, he is redirected to Invoice Page.
However, when user clicks on "Pay Now" button, no API is called.

Please fix this.

PFA screenshot.

**Comment by sagarnankani** [comment]
![paynow.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46f895832d8d94ebc3abaf51ab57f5973d047d317c05f57b2984b42aef1723025d594eac485d5c45f8fe8a79b4aa2e32db025fb28c341521842f1bbeb98515be04b8218a478cbebe8349c3ea2f68.png)

**Comment by apmeena** [comment]
Issue solved.
