### ISSUE TITLE
Invoice Module (Error while searching Invoice)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#599]
Error is received while searching invoice for an account for a partiular date. 
Uncaught TypeError: Cannot read property 'email' of null
at <anonymous>:1:108
at gtm.js?id=GTM-K2L9QG:33
at gtm.js?id=GTM-K2L9QG:34
at gtm.js?id=GTM-K2L9QG:33
at Object.c (gtm.js?id=GTM-K2L9QG:36)
at Sf (gtm.js?id=GTM-K2L9QG:58)
at ll.H (gtm.js?id=GTM-K2L9QG:115)
at vl (gtm.js?id=GTM-K2L9QG:111)
at Lg (gtm.js?id=GTM-K2L9QG:117)
at Yg (gtm.js?id=GTM-K2L9QG:74)
fs.js:34 UserAuthenticated
preview:1 Mixed Content: The page at 'https://giddh.com/app/pages/invoice/preview' was loaded over HTTPS, but requested an insecure favicon 'http://giddh.com/assets/icon/favicon-16x16.png'. This content should also be served over HTTPS.
assets/icon/favicon-16x16.png Failed to load resource: net::ERR_NAME_NOT_RESOLVED
preview:1 Mixed Content: The page at 'https://giddh.com/app/pages/invoice/preview' was loaded over HTTPS, but requested an insecure favicon 'http://giddh.com/assets/icon/android-icon-192x192.png'. This content should also be served over HTTPS.
assets/icon/android-icon-192x192.png Failed to load resource: net::ERR_NAME_NOT_RESOLVED
DevTools failed to parse SourceMap: https://giddh.com/app/assets/css/bootstrap.min.css.map
DevTools failed to parse SourceMap: https://giddh.com/app/assets/css/ngx-bootstrap/bs-datepicker.css.map
DevTools failed to parse SourceMap: https://giddh.com/app/assets/css/perfect-scrollbar.component.css.map

**Comment by sagarnankani** [comment]
PFA screenshot.
![image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c1e5cdf9ad4cae58f3806b1c65262852f37271d2e178ea1a7853595f4ea5445b5e40fbfadb39baa47e21d40854b088270a36d43703adbf881eba03bb248f4f8db7ba894bc3fa70.png)

**Comment by apmeena** [comment]
This error is not related to Invoice module, this is a Google Tag Manager Error.
