### ISSUE TITLE
Inventory Module (Special characters in uniquename issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#611]
In Inventory module, If user clicks on a Group whose uniquename contains special characters, then "400 - Bad Request" error is received from API, and after that if user clicks on any other group, then no API is called.

Please fix this.

ENV: TEST

PFA screenshot for details.

**Comment by sagarnankani** [comment]
![inv_stk_grp_sc.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e19a8c1c9197a2b0eead539b4ef3d665043761260ea62864c7b96aea432d51560e49fe415d5717feff892bafb33f718e5b08bfc3714d36976345f3e5db55ea43a82a994e82bcbd8f4ec1ef3a22e2888c4c3d171755.png)

**Comment by apmeena** [comment]
I have checked it, the problem is because of uniqueName. We have validations now to handle this.
