### ISSUE TITLE
Add & Manage (Incorrect position of Group and empty "permissions" list)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#624]
If user has shared a sub group (say, "Cash") with someone, then, In "Add & Manage" module, "Cash" is being displayed in the fixed groups column.
Also, while sharing the group, when user enters an email id in "Share with" field and then clicks on "Select Permission" drop down, then an empty list is displayed.
Also, If there are other users with whom the entity is shared, then only users' emial ids are displayed. Permission at which the entity is shared with them is not displayed.

ENV: TEST

PFA screenshot.

**Comment by sagarnankani** [comment]
Unable to upload screenshot. I have Shared the same with you on stride.

**Comment by govi2010** [comment]
i'm not able to reproduce it 
can you please take my tv and reproduce this

**Comment by sagarnankani** [comment]
This is not reproducible. Hence, closing this issue.
