### ISSUE TITLE
Permissions module (Incorrect permissions are displayed in "Share" tab)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#625]
In "Permissions" module, if user creates a role with any permission in share scope, and then again clicks on "Add new role" to create a new role and selects "copy from another role" option and selects the newly created role, then Incorrect permissions (Create/Update/Delete) are displayed in "Share" tab.

Please fix this.

**Comment by sagarnankani** [comment]
Please find screenshot on stride.

**Comment by apmeena** [comment]
Done on Test.
