### ISSUE TITLE
Preview and Generate Invoice (Invoice Number issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#626]
ENV: DEV

When user previews invoice, "#######" is displayed in invoice number.
Change required after custom Invoice number functionality:
Unless user doesn't give a custom invoice number, please do not provide invoice number in API.

Please fix this ASAP

**Comment by apmeena** [comment]
What is "custom Invoice number functionality"? Please let me know the condition clearly.

**Comment by apmeena** [comment]
Done
