### ISSUE TITLE
Setings module (Need to remove condition on "Permissions" tab)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#649]
Currently, In Setings module, "Permissions" tab is visible only to SuperAdmin or equivalent level users (Manage -> "Shr" permission is being checked).
Now, since we have a new scope "share" with 3 different permissions for share, we need to remove the condition put on "permissions" tab.
This will enable all users to see the "Permissions" tab.
However, inside permissions tab, list of users with whom company is shared and list of roles that user can assign further, will be filtered according to user's share permission ("shrall", "shrsm" or "shrlwr").

**Comment by sagarnankani** [comment]
@apmeena  Need discussion on this

**Comment by apmeena** [comment]
We are already showing the permission module to `super_admin` only.

- As discussed with @sagarnankani and Shubhendra sir.
