### ISSUE TITLE
Ledger (Get All Ledgers API is not called)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#737]
In Ledger module, if user selects a date range (w/o "Advance Search") and clicks on "Go", data is filtered accordingly.
After this, when user hits "Advance Search" API, data is again filtered.
Now, if user wants to reset all the "Advance Search" filters, he selects (same) date range (w/o "Advance Search") and clicks on "Go", "Get All Ledgers" API is not called. This is incorrect. Even if user selects same date range and clicks on "Go", "Get all ledgers" API should be called, as otherwise user has got no quick option to Reset all the "Advance Search" filters.

**Comment by mustafa-walkover** [comment]
fixed on prod
