### ISSUE TITLE
Upload Attachment (Entry uniquename is not being sent in request)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#794]
ENV: PROD

Entry uniquename is not being sent in request of Upload Attachment API and thus attachment is not getting uploaded on ledger.

PFA screenshot.

Please fix this ASAP as this is a PROD issue.

**Comment by sagarnankani** [comment]
![attch.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e9808e208ac1e5cdf9ad4cae58f3806b1c65262852f37271d2e178ea1a7853595f4ea5445b5e40fbfadb39baa47e21d40854b088270a36d43703adb1881eba03bf23884780bfbe8e4bc7fa70.PNG)

**Comment by mustafa-walkover** [comment]
fixed by @apmeena
