### ISSUE TITLE
Magic Link & Export Ledger (Invalid Date error)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#798]
"Given date is not valid. Provide date in 'dd-MM-yyyy' format Or Entered date is not valid." error message is displayed when user tries to generate magic link or export ledger, since invalid date is being sent from UI end.

PFA screenshots.

ENV: PROD

Please fix this on highest priority as this is a PROD issue.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-04 at 9.46.22 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266454f76b7191a371f1162d4f5d5d5edd3c4a4356bcbbd671f3e57862804e0ebcd76d5625c16f11a9b0d11db901ba298e4c84b2bb891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ee54c56a417316be5702431.png)

**Comment by sagarnankani** [comment]
![date_ml.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ec958e26bd8ea5cda5fd53b652fa912a5265296b51a27d20dce27fbd122e590c5d48ac41515a47fdfd8e28f4a42062c80d55b98e30063e937f03a6aa8318b500bf228e4b84b5bc8344c0e93437aa.PNG)

**Comment by mustafa-walkover** [comment]
fixed by @apmeena
