### ISSUE TITLE
Create Ledger (Incorrect Compound Total value being displayed)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#800]
While creating ledger, Incorrect Compound Total value is being displayed.

ENV: PROD

PFA screenshot.

Please fix this on highest priority.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-04 at 12.11.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266454f76b7191a379ed0c2a50415d46bc21254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29b49c259f349e44954ac12366be472376e0a.png)

**Comment by mustafa-walkover** [comment]
Not-reproducible

**Comment by sagarnankani** [comment]
![Screen Shot 2018-06-05 at 4.41.39 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f66b7191a37cf1162a4f5c565ecc3c4a4356bcbbd671f3e57862804e0ebcd76d5625c16f11a9b0d11db901ba298e4c84b2bb891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df443e04452a0123f62e5772431.png)

**Comment by sagarnankani** [comment]
This is reproducible on PROD. PFA screenshot above. Both the amounts: "1120" and "2293.92" are being concatenated instead of being added.
