### ISSUE TITLE
Create Company (Create button disabled issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#801]
When a new user signs up and verifies his mobile number, "Create Company" pop up is displayed on the next screen, where a loader keeps on moving on "Create" button and the button is disabled, so user can't create a company and move forward.

ENV: PROD

PFA screenshot.

Please fix this on highest priority.

**Comment by mustafa-walkover** [comment]
Not reproducible
