### ISSUE TITLE
Company Settings (Financial Year Issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#806]
ENV: PROD

In Company Settings tab, under "Financial Year" tab, when user clicks on "Add Financial Year" drop down, "FY 2017-2018" option is not available in the list.

This list should be populated dynamically on UI and should show options for previous 6 financial years.

PFA screenshot for details.

Please fix this ASAP.

**Comment by sagarnankani** [comment]
![fy17.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ee8dcb74c0cfeb9ffbb049a15ee4d6730472727f54fa2a2787b37de74129575f5f47a942595b43ffab9b37b4f46d2ede0356b49b381d66cc2f10a4b2831abd04be29824787b1bd8e4dd2a5.PNG)

**Comment by sagarnankani** [comment]
Correction: This list should be populated dynamically on UI and should show options for previous 7 financial years.

**Comment by mustafa-walkover** [comment]
done
