### ISSUE TITLE
Data Refresh Issue

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#807]
ENV: PROD

Data is not getting refreshed automatically and user has to refresh the page manually almost after every operation.

For example, after creating a new company, user has to refresh the company list or page manually. This is incorrect. User should be switched to newly created company as soon as it is created.

Please fix this ASAP as this is a PROD issue.

**Comment by sagarnankani** [comment]
![image (10).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1deb9f601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00b32a8a4a87b0bf8c45c2ef382dee8d9d02.png)

Inventory items being displayed in "Product/Service" drop down, do not belong to the company being displayed on top (LOCUST). They belong to the previous company on which user was working.
Please fix this ASAP.

**Comment by mustafa-walkover** [comment]
done

**Comment by sagarnankani** [comment]
Checked on Test. Issue persists.

**Comment by sagarnankani** [comment]
Also, move the cards when they're done.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-09-17 at 10.59.17 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455f46b7191a379ef0c2e58415e49bc30254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e64c53a6163064e27f3f6e0a.png)

**Comment by sagarnankani** [comment]
Issue persists. PFA screenshot in above comment.

**Comment by sagarnankani** [comment]
If an account exists in Company A with unique name "punjabnationalbank9176" and the same ledger is open on UI, then if user creates a new company, same account uniquename : "punjabnationalbank9176"is passed in API URL with newly created company uniquename, because of ACCOUNT_NOT_FOUND error is received in response. Please fix this.
