### ISSUE TITLE
Sales Module (Incorrect account unique name issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#808]
In Sales Module, Even when user selects a Debtor Account, Incorrect account unique name ("cash") is being passed in request body.

Please fix this ASAP as this is a PROD issue.

PFA screenshot for details.

**Comment by sagarnankani** [comment]
Unable to attach screenshot presently.

Please find request body below. Notice that "cash" is being passed in "uniqueName" key in  "accountDetails" object.

{
	"voucher": {
		"accountDetails": {
			"country": {
				"countryName": "India",
				"countryCode": "IN"
			},
			"billingDetails": {
				"address": ["Bihar"],
				"stateCode": "10",
				"gstNumber": ""
			},
			"shippingDetails": {
				"address": [""],
				"stateCode": "10",
				"gstNumber": ""
			},
			"name": "abcd test",
			"uniqueName": "cash",
			"attentionTo": "",
			"email": null,
			"mobileNumber": null
		},
		"entries": [{
			"transactions": [{
				"stockList": [],
				"applicableTaxes": [],
				"taxRenderData": [],
				"amount": 3000,
				"total": 3000,
				"isStockTxn": false,
				"hsnOrSac": "sac",
				"date": "05-05-2018",
				"taxableValue": 3000,
				"fakeAccForSelect2": "8492d9bf-9799-4b99-91f7-01f6405dc73e",
				"quantity": null,
				"accountName": "Tution Service",
				"accountUniqueName": "tutionservice",
				"hsnNumber": null,
				"sacNumber": null,
				"stockUnit": null,
				"stockDetails": null,
				"rate": null,
				"description": "For April Month"
			}],
			"taxes": [],
			"taxList": [],
			"discounts": [],
			"taxSum": 0,
			"discountSum": 0,
			"voucherType": "Sales"
		}, {
			"transactions": [{
				"stockList": [],
				"applicableTaxes": [],
				"taxRenderData": [],
				"amount": 1500,
				"total": 1500,
				"isStockTxn": false,
				"hsnOrSac": "sac",
				"date": "05-05-2018",
				"taxableValue": 1500,
				"fakeAccForSelect2": "07b59294-3904-42e6-b392-b13621ca4aba",
				"quantity": null,
				"accountName": "Transportation CHarges",
				"accountUniqueName": "transportationcharges",
				"hsnNumber": null,
				"sacNumber": null,
				"stockUnit": null,
				"stockDetails": null,
				"rate": null,
				"description": "For April Month"
			}],
			"taxes": [],
			"taxList": [],
			"discounts": [],
			"taxSum": 0,
			"discountSum": 0,
			"voucherType": "Sales"
		}],
		"voucherDetails": {
			"customerName": "abcd test",
			"grandTotal": 4500,
			"subTotal": 4500,
			"totalAsWords": null,
			"voucherDate": "05-05-2018",
			"dueDate": "15-05-2018",
			"totalDiscount": 0,
			"totalTaxableValue": 4500,
			"gstTaxesTotal": 0,
			"balanceDue": 4500
		},
		"templateDetails": {
			"other": {
				"shippingDate": "",
				"shippedVia": null,
				"trackingNumber": null,
				"customField1": null,
				"customField2": null,
				"customField3": null,
				"message2": null
			}
		}
	},
	"updateAccountDetails": true
}

**Comment by mustafa-walkover** [comment]
fix on prod
