### ISSUE TITLE
Company Settings - Financial Year (No Record Found)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#816]
In Company Settings, under Financial Year tab, "No Record Found" message is displayed.
This is incorrect. Atleast one record for current FY should be displayed.

ENV: PROD

PFA screenshot.

Please fix this on priority.

**Comment by sagarnankani** [comment]
![image (7).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1d8a0fd0fe64de29b234324676b5ee17e71d3b371be1579515a571dae47585f4df9fa882fa1b56e62964e49bc8f3900299f7744eeaa880dbe06b0218e4d80b3be8249c2e13c22e499c2.png)

**Comment by mustafa-walkover** [comment]
done
