### ISSUE TITLE
Ledger  - Bank Details ("Something Went Wrong")

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#832]
"Something Went Wrong please reload page" error message appears on Ledger, while viewing Bank Details.
ENV: PROD
PFA screenshot for details.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-08 at 2.46.17 PM (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266454fb6b7191a37af1162d4f5e585ecc3c484745e5eb9539e6f4632adf0f4fffdb7f5a25c03d18fdbfd01fba09e9228d4f85bfb9894dc4ef3e77f5979d0d6f405147d4a61760e28b41da59ff41e04857a1143161e170357b4f960c38.png)

**Comment by mustafa-walkover** [comment]
done
