### ISSUE TITLE
Sign Up (Mobile Verification process skipped)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#833]
After signing up, if user doesn't verify his number, logs out from giddh and then logs in again (Connect With Google), Mobile Verification process is skipped. Create Company pop up appears directly without mobile number verification.

Please find link for video below.
https://fsty.io/v/3XNtcTM

ENV: PROD

**Comment by mustafa-walkover** [comment]
checked, not persist now.. confirmed by devendra ojha
