### ISSUE TITLE
Create Ledger (Multiple API calls)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#844]
Multiple API calls are made while creating ledger, hence multiple entries are created with same data.
PFA screenshot.
ENV: PROD
Please fix this ASAP as this is a PROD issue.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-09 at 3.00.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266454fa6b7191a37bf1122b4f5b5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd76d5625c16f11a9b0d11db901ba298e4c84b2bb891ed2f42f67b6d5db1063474f4dcbed5727a29941c95df44ee9485da0173264e0712431.png)

**Comment by mustafa-walkover** [comment]
This is not multiple API call, 1st URL is for options & 2nd  to save entry

**Comment by mustafa-walkover** [comment]
@sagarnankani closing this card as no response received on this card
