### ISSUE TITLE
Menu Bar (Need scroll bar)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#846]
Need scroll bar for the menu bar on the left.
PFA screenshot.

**Comment by sagarnankani** [comment]
![scroll.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46fb97882c8e8febc3abaf51ab57f5973d047d317c05f57b2984b42aef1723025d594eac485d5c45f8fe8a79b4aa2e32db025fb28c341521842f1bbeb98415be04b825824c81b1b58249c1e12f68.PNG)

**Comment by mustafa-walkover** [comment]
done
