### ISSUE TITLE
Sales Module (Application hangs while creating debtor)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#847]
In Sales module, while trying to create a new debtor, loader appeared with "Something wentwrong, please reload the page" error message and then application hung up.
User had to kill the page and login again.

Please find full story video link below.

ENV: PROD

Please fix this issue at the earliest.

**Comment by sagarnankani** [comment]
https://fsty.io/v/KLBHrEt

**Comment by mustafa-walkover** [comment]
Not-Reproducible
