### ISSUE TITLE
Edit Invoice Template (Application getting hung up)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#848]
While editing an invoice template, when user tries to change the font, "Loading fonts list" message doesn't go away and then application hangs up.
PFA screenshot.
 
ENV: PROD

Please fix this on highest priority.

**Comment by sagarnankani** [comment]
![SS1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46dba7cb61cec1b99de6b546a749b2ce6b132625795da27c72d5b670bc102d515f564baf405c5847aeeb9539e4e76224d50152a7842f4d7ed43c16a6b9871dba08b9298c4e80b5b98f5e8d.png)

**Comment by mustafa-walkover** [comment]
Not-Reproducible
