### ISSUE TITLE
Manufacturing (Same account name & uniquename are being displayed multiple times)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#850]
In Manufacturing module, under Total Cost tab, Same account name & uniquename are being displayed multiple times in Expenses Drop down.
PFA screenshot.
ENV: PROD
Please fix this on highest priority.

**Comment by sagarnankani** [comment]
![image (8).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1d7a0fd0fe64de29b234324676b5ee17e71d3b371be1579515a571dae47585f4df9fa882fa1b56e62964e49bc8f3900299f7744eeaa880dbe06b0218e4d80bfb98848c3ef3f22e799c2.png)

**Comment by mustafa-walkover** [comment]
@walkover101 cannot replicate the issue

**Comment by mustafa-walkover** [comment]
Not-Reproducible
