### ISSUE TITLE
Electron App (Unable to paste)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#851]
User is unable to copy/paste anything from/to "Description", "Amount" or any other fields.
PFA screenshot.
Please fix this on highest priority.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-11 at 12.05.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f26b7191a379ed0c2b54415e4fbc21254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e74d57a4153463e677326e0a.png)

**Comment by mustafa-walkover** [comment]
It is working in latest version, approved by devendra ojha
