### ISSUE TITLE
Sign up and number verification issues

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#867]
When a new user clicks on "Sign Up" button, instead of getting the "email and password" pop-up, he gets into the application directly.
Also, after this when user enters his number, clicks on "Add" and then clicks on the close button, logs out of application and then again logs in, "Enter Verification Code" is still displayed. This is incorrect. Once user logs out & then logs in again, only "Add Mobile Number" field should be displayed.

ENV: PROD

Please find full story video link below.
https://fsty.io/v/Q9BtTaq

Please fix this on highest priority.

**Comment by mustafa-walkover** [comment]
done
