### ISSUE TITLE
Contacts Module (Data refresh issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#870]
In contacts module, data is not getting refreshed as "refresh=true" param is not being sent in Account Balances API URL.
When user comes to Contacts module from some other module, "refresh=true" param should be sent in request URL.

PFA screenshot for details.

ENV: PROD
Please fix this on high priority.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-16 at 11.12.27 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379ee0c2a53415d49bc30254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e74950a41a3f64e0773e6e0a.png)

**Comment by sagarnankani** [comment]
Newly added customers/vendors are also not found if refresh=true param is not sent in request URL

**Comment by mustafa-walkover** [comment]
done by arpit
