### ISSUE TITLE
Sales module (Recurring API is not being called)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#882]
In Sales module, Recurring tab, after entering all the recurring details when user clicks on "Save" button, Recurring API is not called.

ENV: PROD

Please fix this on highest priority.

PFA screenshot.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-21 at 11.05.14 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f26b7191a379ee0c2b54415e4abc30254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e7455da6123762e170316e0a.png)

**Comment by mustafa-walkover** [comment]
done
