### ISSUE TITLE
Sales Module (Drop Down issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#884]
In Sales module, size of the "State" drop down is too small. All the list items are getting cropped.

ENV: PROD

Please fix this issue on high priority.

PFA screenshot.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-21 at 10.57.28 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f26b7191a379ef0c2e56415d46bc30254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e7455da0143563e2703f6e0a.png)

**Comment by mustafa-walkover** [comment]
done
