### ISSUE TITLE
Ledger (Particular is not being displayed)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#885]
When user double clicks on a ledger, a pop up opens up with ledger details. "Sales" Particular is not being displayed in the pop up.

ENV: PROD

Please fix this ASAP.

PFA screenshot.

Please note that the particular is being received in response of API.

//API Details:
//URL
Get http://api.giddh.com/company/itelyindore152687474987808wgu6/accounts/amazonfba/ledgers/awn1526884911474

//Response
{"status":"success","body":{"transactions":[{"particular":{"name":"Local Sales @  18%","uniqueName":"localsales@18%"},"amount":334.75,"convertedAmount":null,"convertedAmountCurrency":null,"type":"DEBIT","inventory":{"stock":{"name":"Wow Hair Conditioner","uniqueName":"wowhairconditioner"},"quantity":1.0000,"amount":334.7500,"rate":334.75,"unit":{"code":"nos","hierarchicalQuantity":1.0000,"parentStockUnit":null,"quantityPerUnit":1.0000,"name":"Num"},"warehouse":null,"stockLocation":null},"isTax":false,"isBaseAccount":false},{"particular":{"name":"IGST (gst)","uniqueName":"igstgst"},"amount":60.26,"convertedAmount":null,"convertedAmountCurrency":null,"type":"DEBIT","inventory":null,"isTax":true,"isBaseAccount":false}],"total":{"amount":395.01,"type":"DEBIT"},"tagNames":[],"uniqueName":"awn1526884911474","entryDate":"08-04-2018","taxes":["gst"],"invoiceNumberAgainstVoucher":null,"voucher":{"name":"sales","shortCode":"sal"},"voucherNo":11850,"attachedFile":"","sendToGstr2":true,"availItc":true,"warning":null,"chequeNumber":"","voucherNumber":"20180408-1055","unconfirmedEntry":false,"voucherGenerated":true,"chequeClearanceDate":"","linkedInvoices":[],"attachedFileName":"","description":null,"tag":null}}

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-21 at 1.01.36 PM (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f26b7191a379f1122a4f5c595ecc3c484745e5eb9539e6f4632adf0f4fffdb7f5a25c03d18fdbfd01fba09e9228d4f85bfb9894dc4ef3e77f5979d0d6f405147d4a61760e28b41da59ff41e04857a21b3e6be4723574429c0c38.png)

**Comment by mustafa-walkover** [comment]
cannot reproduce bug, due to CORS issue from API

**Comment by mustafa-walkover** [comment]
cannot reproduce bug
