### ISSUE TITLE
Generate Sales Module (Cash or Bank can not be updated)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#900]
In Generate Sales Module, "Cash or Bank can not be updated" error message is received, even when user selects a Debtor's account and clicks on "Generate Invoice & Update Account".
This is because incorrect account unique name: "cash" is being passed in API URL, instead of Debtor's account unique name.

ENV: PROD
Please fix this ASAP.

PFA screenshots.

**Comment by mustafa-walkover** [comment]
checked it on deepak PC, cannot reproduce it

**Comment by apmeena** [comment]
This issue is already fixed by @mustafa-walkover
