### ISSUE TITLE
Create Ledger (Drop Down issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#910]
While creating ledger entry, empty drop down list is displayed when user clicks on Particulars field.
Cross button at right side of Particulars field is also not working.

Amount field is also blank.

ENV: TEST

PFA screenshot.

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-31 at 11.55.22 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266457f26b7191a379ee0c2e54415d4cbc30254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e64a51ac1a3261e474316e0a.png)

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-31 at 11.55.26 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266457f26b7191a379ee0c2e54415d48bc30254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e64a51ad133667e370356e0a.png)

**Comment by sagarnankani** [comment]
![Screen Shot 2018-05-31 at 12.14.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266457f26b7191a379ed0c2a55415f4fbc21254d58eeb9cb74fce36f34985619e8806b5f7d973a43acbd8a4cbd07ba20824a86b7b88d4f92fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e64a51ad13306ae774356e0a.png)

**Comment by mustafa-walkover** [comment]
is not reproducible now, checked

**Comment by mustafa-walkover** [comment]
fixed on prod
