### ISSUE TITLE
Profit and Loss (Taxes in case of Loss)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#917]
In Profit and Loss Report, if value of "Income Before Taxes" is negative, then value of "tax" query param should be "0".

//API URL:
Request URL: http://apitest.giddh.com/company/balancindore15278388776190re48l/v3/profit-loss?tax=30&from=01-04-2018&to=31-03-2019&fy=0&selectedDateOption=0&selectedFinancialYearOption=FY-APR2018-MAR2019&refresh=true
Request Method: GET

**Comment by mustafa-walkover** [comment]
No need to work on it, as per discussion with @sagarnankani, incomeBeforeTax value is getting in the same API
