### ISSUE TITLE
Contacts Module (Need Refresh Button)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#922]
In Contacts Module, "Refresh" Button is required and when user clicks on this button, only then "refresh=true" query param should be sent in Request URLs of Account Balances APIs, otherwise "refresh=false" query param should be sent by default.

ENV: PROD

//API URLs:
Request URL: https://api.giddh.com/v2/company/walkpvindore14504197149880siqli/groups/sundrydebtors/account-balances?page=1&count=20&refresh=true

Request URL: https://api.giddh.com/v2/company/walkpvindore14504197149880siqli/groups/sundrycreditors/account-balances?page=1&count=20&refresh=true

**Comment by sagarnankani** [comment]
Also, API to check account balances of all accounts in Sundry Creditors group should be called only when user clicks on "Vendors" button. Currently, it is called as soon as user goes to "Contacts" module.

**Comment by mustafa-walkover** [comment]
done
