### ISSUE TITLE
Sales Module (Need hsn field)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#934]
While adding a new product from Sales module, "HSN" field is not available in sidebar.

ENV: PROD
Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![hsn_needed.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e087941c8c86ac8becbb01e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00b22a8a4a87bebe8d4bc6ef3c20e58a9d02.PNG)

**Comment by mustafa-walkover** [comment]
done
