### ISSUE TITLE
User Profile Page (Mobile Number Format error)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#936]
On User Profile Page, Mobile Number of user is displayed in "917777777777" format. However, when user tries to edit the number and provides contact number in same format, following error message is displayed: "Please enter number in format: 9998899988".

Also, "Note: Format should be like 9898989898" text is displayed below the mobile number field.

If number should be in "9998899988" format, please display it in the same format in mobile number field.

ENV: PROD

Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![mobile_format.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e59b982a8e869689e6ad4ea549b2d86b56357c2301a03f32dfa17dbe142b580e581cac44500c46faf98922a3b53d748d5f59ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98844c3ef3e23e08f88463a0c48.png)

**Comment by apmeena** [comment]
Fixed.
