### ISSUE TITLE
Sales module (State field issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#940]
When user tries to create an account from Sales module, "State code is mandatory for sundry debtors and creditors" error message is displayed, even when state code is being displayed in "State" field.

This happens because state is only being displayed in state field, but value is actually not selected (notice that "cross" icon is not displayed at the right side of the field).

PFA screenshot.

ENV: PROD

Please fix this on high priority.

**Comment by sagarnankani** [comment]
![image (12).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e1999b2487c3e1debbf601e81fe086264c22703d46f9692584b578e6432c035f5a46ff435e5f44f5fc8a2aa2b13f22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a87bebb8b4bc7e13e26e18f9d02.png)

**Comment by mustafa-walkover** [comment]
not reproducible

**Comment by Eagle-Giddh** [comment]
Currently working fine on Prod
