### ISSUE TITLE
Create/Update Ledger - Incorrect (Currency Converter) API call

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#952]
While creating/updating ledger, Incorrect currency converter API is being called from UI end and hence "Invalid API" error message is received in response. 

ENV: PROD

Please fix this ASAP.

Correct API Details:
{{url}}/company/{{companyUniqueName}}/currency-converter/{fromCurrency}/{toCurrency}
GET API
Response :
{
   "status": "success",
   "body": 68.22
}

**Comment by apmeena** [comment]
`'company/:companyUniqueName/curreny-converter/:fromCurrency/:toCurrency'` spelling mistake in API URL, it creates confusion while debugging the code. be careful for spellings.
