### ISSUE TITLE
Inventory Module ("Save" Button issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#957]
In Inventory Module, while creating a stock, after providing all the necessary details, when user clicks on "Save" button, it should be disabled, until a response is received from API end or for a specific time period (let's say 30 seconds).

Currently, "Save" button isn't disabled, so if user double-clicks on "Save" button, multiple requests are sent to server at the same time and "500 - Internal Server Error" is received in response.

ENV: PROD
Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![test_multiplle_api_call.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46fc918937bd8ebc83fdb653a851f5ab28562e4c2a05af2732c9a138ad4d71040c1b5ca6535d0e42fcf0d82cf4b63978d95e0dedd1645a77c73916afea9003ad43eb7edf10d8eff6df0ed2e22f24ee818e4a3c1706198ff75c36a1904fda15.PNG)

**Comment by mustafa-walkover** [comment]
not reproducible, checked on prod
