### ISSUE TITLE
Create Ledger/ Generate Voucher (Need to select taxes priority wise)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#960]
While creating ledger or generating a voucher, taxes should be checked according to following priority order.

P1. Stock Account
P2. Stock Group
P3. Income/Expenses category Account
P4.Income/Expenses category Group

That is, if taxes are applied on the stock, then (only) these taxes will be selected in the "taxes" drop down list. If no taxes are found on stock account, then taxes will be checked on stock group. If taxes are found here, then (only) these taxes will be selected. Likewise, we will check & select taxes on income/expense category account (sales, purchases, etc.) and then income/expense category group (sales, purchases, etc.).

Currently, all the taxes applied on income/expense category account and group are selected, which is incorrect.

ENV: PROD

Note: This is fixed from API end. So please fix this from UI end urgently, so that we can deploy this on PROD.

**Comment by apmeena** [comment]
I worked on it, but this is not completed, some work from the API side needs to be done.

**Comment by sagarnankani** [comment]
Checked on Test. Issue Persists.

**Comment by sagarnankani** [comment]
@mustafa-walkover I don't think you will require anything from API end to fix this.

**Comment by sagarnankani** [comment]
Related card: card no. 246 on goodday.

**Comment by mustafa-walkover** [comment]
closing this card
