### ISSUE TITLE
Search Accounts (Multiple API calls)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#983]
e-ledgers API is being called multiple times when user searches for an account.

ENV: STAGE

PFA screenshot

**Comment by sagarnankani** [comment]
![multiple_call_eledger.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46e58196378b93a58ad6bc42a851cf91254323742c16e1673295f127b54778154d555ca9105e5f4dadfedb2ba3be6f728c5c0be4d46e5e70c13e43bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8c4f3c1b061b8af95d37a68b06.PNG)

**Comment by mustafa-walkover** [comment]
Checked on STAGE, single time API is calling
